/* Generated by Yosys 0.60 (git sha1 5bafeb77dc71e054fa331ab9efa613e6fb0a1c49, clang++ 17.0.0 -fPIC -O3) */

(* top =  1  *)
(* src = "src/Mega/interface_unit.sv:3.1-130.10" *)
module interface_unit(clk, rst_n, rx_valid_n, rx_valid_s, rx_valid_e, rx_valid_w, rx_ready_n, rx_ready_s, rx_ready_e, rx_ready_w, tx_valid_n, tx_valid_s, tx_valid_e, tx_valid_w, tx_ready_n, tx_ready_s, tx_ready_e, tx_ready_w, diverge_req, diverge_target, diverge_lit
, diverge_ack, force_valid, force_lit, force_ready, clause_bcast_req, clause_lbd, clause_ptr, clause_bcast_ack, clause_rx_valid, clause_rx_lbd, clause_rx_ptr, clause_rx_ready, rx_pkt_n, rx_pkt_s, rx_pkt_e, rx_pkt_w, tx_pkt_n, tx_pkt_s, tx_pkt_e, tx_pkt_w);
  (* src = "src/Mega/interface_unit.sv:7.18-7.21" *)
  input clk;
  wire clk;
  (* src = "src/Mega/interface_unit.sv:8.18-8.23" *)
  input rst_n;
  wire rst_n;
  (* src = "src/Mega/interface_unit.sv:15.18-15.28" *)
  input rx_valid_n;
  wire rx_valid_n;
  (* src = "src/Mega/interface_unit.sv:15.30-15.40" *)
  input rx_valid_s;
  wire rx_valid_s;
  (* src = "src/Mega/interface_unit.sv:15.42-15.52" *)
  input rx_valid_e;
  wire rx_valid_e;
  (* src = "src/Mega/interface_unit.sv:15.54-15.64" *)
  input rx_valid_w;
  wire rx_valid_w;
  (* src = "src/Mega/interface_unit.sv:16.18-16.28" *)
  output rx_ready_n;
  wire rx_ready_n;
  (* src = "src/Mega/interface_unit.sv:16.30-16.40" *)
  output rx_ready_s;
  wire rx_ready_s;
  (* src = "src/Mega/interface_unit.sv:16.42-16.52" *)
  output rx_ready_e;
  wire rx_ready_e;
  (* src = "src/Mega/interface_unit.sv:16.54-16.64" *)
  output rx_ready_w;
  wire rx_ready_w;
  (* src = "src/Mega/interface_unit.sv:23.18-23.28" *)
  output tx_valid_n;
  wire tx_valid_n;
  (* src = "src/Mega/interface_unit.sv:23.30-23.40" *)
  output tx_valid_s;
  wire tx_valid_s;
  (* src = "src/Mega/interface_unit.sv:23.42-23.52" *)
  output tx_valid_e;
  wire tx_valid_e;
  (* src = "src/Mega/interface_unit.sv:23.54-23.64" *)
  output tx_valid_w;
  wire tx_valid_w;
  (* src = "src/Mega/interface_unit.sv:24.18-24.28" *)
  input tx_ready_n;
  wire tx_ready_n;
  (* src = "src/Mega/interface_unit.sv:24.30-24.40" *)
  input tx_ready_s;
  wire tx_ready_s;
  (* src = "src/Mega/interface_unit.sv:24.42-24.52" *)
  input tx_ready_e;
  wire tx_ready_e;
  (* src = "src/Mega/interface_unit.sv:24.54-24.64" *)
  input tx_ready_w;
  wire tx_ready_w;
  (* src = "src/Mega/interface_unit.sv:27.25-27.36" *)
  input diverge_req;
  wire diverge_req;
  (* src = "src/Mega/interface_unit.sv:28.25-28.39" *)
  input [3:0] diverge_target;
  wire [3:0] diverge_target;
  (* src = "src/Mega/interface_unit.sv:29.32-29.43" *)
  input [31:0] diverge_lit;
  wire [31:0] diverge_lit;
  (* src = "src/Mega/interface_unit.sv:30.25-30.36" *)
  output diverge_ack;
  wire diverge_ack;
  (* src = "src/Mega/interface_unit.sv:33.25-33.36" *)
  output force_valid;
  wire force_valid;
  (* src = "src/Mega/interface_unit.sv:34.32-34.41" *)
  output [31:0] force_lit;
  wire [31:0] force_lit;
  (* src = "src/Mega/interface_unit.sv:35.25-35.36" *)
  input force_ready;
  wire force_ready;
  (* src = "src/Mega/interface_unit.sv:38.25-38.41" *)
  input clause_bcast_req;
  wire clause_bcast_req;
  (* src = "src/Mega/interface_unit.sv:39.25-39.35" *)
  input [7:0] clause_lbd;
  wire [7:0] clause_lbd;
  (* src = "src/Mega/interface_unit.sv:40.25-40.35" *)
  input [63:0] clause_ptr;
  wire [63:0] clause_ptr;
  (* src = "src/Mega/interface_unit.sv:41.25-41.41" *)
  output clause_bcast_ack;
  wire clause_bcast_ack;
  (* src = "src/Mega/interface_unit.sv:44.25-44.40" *)
  output clause_rx_valid;
  wire clause_rx_valid;
  (* src = "src/Mega/interface_unit.sv:45.25-45.38" *)
  output [7:0] clause_rx_lbd;
  wire [7:0] clause_rx_lbd;
  (* src = "src/Mega/interface_unit.sv:46.25-46.38" *)
  output [63:0] clause_rx_ptr;
  wire [63:0] clause_rx_ptr;
  (* src = "src/Mega/interface_unit.sv:47.25-47.40" *)
  input clause_rx_ready;
  wire clause_rx_ready;
  (* src = "src/Mega/interface_unit.sv:11.41-11.49" *)
  (* wiretype = "\\satswarmv2_pkg::noc_packet_t" *)
  input [79:0] rx_pkt_n;
  wire [79:0] rx_pkt_n;
  (* src = "src/Mega/interface_unit.sv:12.41-12.49" *)
  (* wiretype = "\\satswarmv2_pkg::noc_packet_t" *)
  input [79:0] rx_pkt_s;
  wire [79:0] rx_pkt_s;
  (* src = "src/Mega/interface_unit.sv:13.41-13.49" *)
  (* wiretype = "\\satswarmv2_pkg::noc_packet_t" *)
  input [79:0] rx_pkt_e;
  wire [79:0] rx_pkt_e;
  (* src = "src/Mega/interface_unit.sv:14.41-14.49" *)
  (* wiretype = "\\satswarmv2_pkg::noc_packet_t" *)
  input [79:0] rx_pkt_w;
  wire [79:0] rx_pkt_w;
  (* src = "src/Mega/interface_unit.sv:19.41-19.49" *)
  (* wiretype = "\\satswarmv2_pkg::noc_packet_t" *)
  output [79:0] tx_pkt_n;
  wire [79:0] tx_pkt_n;
  (* src = "src/Mega/interface_unit.sv:20.41-20.49" *)
  (* wiretype = "\\satswarmv2_pkg::noc_packet_t" *)
  output [79:0] tx_pkt_s;
  wire [79:0] tx_pkt_s;
  (* src = "src/Mega/interface_unit.sv:21.41-21.49" *)
  (* wiretype = "\\satswarmv2_pkg::noc_packet_t" *)
  output [79:0] tx_pkt_e;
  wire [79:0] tx_pkt_e;
  (* src = "src/Mega/interface_unit.sv:22.41-22.49" *)
  (* wiretype = "\\satswarmv2_pkg::noc_packet_t" *)
  output [79:0] tx_pkt_w;
  wire [79:0] tx_pkt_w;
  wire _0000_;
  wire _0001_;
  wire _0002_;
  wire _0003_;
  wire _0004_;
  wire _0005_;
  wire _0006_;
  wire _0007_;
  wire _0008_;
  wire _0009_;
  wire _0010_;
  wire _0011_;
  wire _0012_;
  wire _0013_;
  wire _0014_;
  wire _0015_;
  wire _0016_;
  wire _0017_;
  wire _0018_;
  wire _0019_;
  wire _0020_;
  wire _0021_;
  wire _0022_;
  wire _0023_;
  wire _0024_;
  wire _0025_;
  wire _0026_;
  wire _0027_;
  wire _0028_;
  wire _0029_;
  wire _0030_;
  wire _0031_;
  wire _0032_;
  wire _0033_;
  wire _0034_;
  wire _0035_;
  wire _0036_;
  wire _0037_;
  wire _0038_;
  wire _0039_;
  wire _0040_;
  wire _0041_;
  wire _0042_;
  wire _0043_;
  wire _0044_;
  wire _0045_;
  wire _0046_;
  wire _0047_;
  wire _0048_;
  wire _0049_;
  wire _0050_;
  wire _0051_;
  wire _0052_;
  wire _0053_;
  wire _0054_;
  wire _0055_;
  wire _0056_;
  wire _0057_;
  wire _0058_;
  wire _0059_;
  wire _0060_;
  wire _0061_;
  wire _0062_;
  wire _0063_;
  wire _0064_;
  wire _0065_;
  wire _0066_;
  wire _0067_;
  wire _0068_;
  wire _0069_;
  wire _0070_;
  wire _0071_;
  wire _0072_;
  wire _0073_;
  wire _0074_;
  wire _0075_;
  wire _0076_;
  wire _0077_;
  wire _0078_;
  wire _0079_;
  wire _0080_;
  wire _0081_;
  wire _0082_;
  wire _0083_;
  wire _0084_;
  wire _0085_;
  wire _0086_;
  wire _0087_;
  wire _0088_;
  wire _0089_;
  wire _0090_;
  wire _0091_;
  wire _0092_;
  wire _0093_;
  wire _0094_;
  wire _0095_;
  wire _0096_;
  wire _0097_;
  wire _0098_;
  wire _0099_;
  wire _0100_;
  wire _0101_;
  wire _0102_;
  wire _0103_;
  wire _0104_;
  wire _0105_;
  wire _0106_;
  wire _0107_;
  wire _0108_;
  wire _0109_;
  wire _0110_;
  wire _0111_;
  wire _0112_;
  wire _0113_;
  wire _0114_;
  wire _0115_;
  wire _0116_;
  wire _0117_;
  wire _0118_;
  wire _0119_;
  wire _0120_;
  wire _0121_;
  wire _0122_;
  wire _0123_;
  wire _0124_;
  wire _0125_;
  wire _0126_;
  wire _0127_;
  wire _0128_;
  wire _0129_;
  wire _0130_;
  wire _0131_;
  wire _0132_;
  wire _0133_;
  wire _0134_;
  wire _0135_;
  wire _0136_;
  wire _0137_;
  wire _0138_;
  wire _0139_;
  wire _0140_;
  wire _0141_;
  wire _0142_;
  wire _0143_;
  wire _0144_;
  wire _0145_;
  wire _0146_;
  wire _0147_;
  wire _0148_;
  wire _0149_;
  wire _0150_;
  wire _0151_;
  wire _0152_;
  wire _0153_;
  wire _0154_;
  wire _0155_;
  wire _0156_;
  wire _0157_;
  wire _0158_;
  wire _0159_;
  wire _0160_;
  wire _0161_;
  wire _0162_;
  wire _0163_;
  wire _0164_;
  wire _0165_;
  wire _0166_;
  wire _0167_;
  wire _0168_;
  wire _0169_;
  wire _0170_;
  wire _0171_;
  wire _0172_;
  wire _0173_;
  wire _0174_;
  wire _0175_;
  wire _0176_;
  wire _0177_;
  wire _0178_;
  wire _0179_;
  wire _0180_;
  wire _0181_;
  wire _0182_;
  wire _0183_;
  wire _0184_;
  wire _0185_;
  wire _0186_;
  wire _0187_;
  wire _0188_;
  wire _0189_;
  wire _0190_;
  wire _0191_;
  wire _0192_;
  wire _0193_;
  wire _0194_;
  wire _0195_;
  wire _0196_;
  wire _0197_;
  wire _0198_;
  wire _0199_;
  wire _0200_;
  wire _0201_;
  wire _0202_;
  wire _0203_;
  wire _0204_;
  wire _0205_;
  wire _0206_;
  wire _0207_;
  wire _0208_;
  wire _0209_;
  wire _0210_;
  wire _0211_;
  wire _0212_;
  wire _0213_;
  wire _0214_;
  wire _0215_;
  wire _0216_;
  wire _0217_;
  wire _0218_;
  wire _0219_;
  wire _0220_;
  wire _0221_;
  wire _0222_;
  wire _0223_;
  wire _0224_;
  wire _0225_;
  wire _0226_;
  wire _0227_;
  wire _0228_;
  wire _0229_;
  wire _0230_;
  wire _0231_;
  wire _0232_;
  wire _0233_;
  wire _0234_;
  wire _0235_;
  wire _0236_;
  wire _0237_;
  wire _0238_;
  wire _0239_;
  wire _0240_;
  wire _0241_;
  wire _0242_;
  wire _0243_;
  wire _0244_;
  wire _0245_;
  wire _0246_;
  wire _0247_;
  wire _0248_;
  wire _0249_;
  wire _0250_;
  wire _0251_;
  wire _0252_;
  wire _0253_;
  wire _0254_;
  wire _0255_;
  wire _0256_;
  wire _0257_;
  wire _0258_;
  wire _0259_;
  wire _0260_;
  wire _0261_;
  wire _0262_;
  wire _0263_;
  wire _0264_;
  wire _0265_;
  wire _0266_;
  wire _0267_;
  wire _0268_;
  wire _0269_;
  wire _0270_;
  wire _0271_;
  wire _0272_;
  wire _0273_;
  wire _0274_;
  wire _0275_;
  wire _0276_;
  wire _0277_;
  wire _0278_;
  wire _0279_;
  wire _0280_;
  wire _0281_;
  wire _0282_;
  wire _0283_;
  wire _0284_;
  wire _0285_;
  wire _0286_;
  wire _0287_;
  wire _0288_;
  wire _0289_;
  wire _0290_;
  wire _0291_;
  wire _0292_;
  wire _0293_;
  wire _0294_;
  wire _0295_;
  wire _0296_;
  wire _0297_;
  wire _0298_;
  wire _0299_;
  wire _0300_;
  wire _0301_;
  wire _0302_;
  wire _0303_;
  wire _0304_;
  wire _0305_;
  wire _0306_;
  wire _0307_;
  wire _0308_;
  wire _0309_;
  wire _0310_;
  wire _0311_;
  wire _0312_;
  wire _0313_;
  wire _0314_;
  wire _0315_;
  wire _0316_;
  wire _0317_;
  wire _0318_;
  wire _0319_;
  wire _0320_;
  wire _0321_;
  wire _0322_;
  wire _0323_;
  wire _0324_;
  wire _0325_;
  wire _0326_;
  wire _0327_;
  wire _0328_;
  wire _0329_;
  wire _0330_;
  wire _0331_;
  wire _0332_;
  wire _0333_;
  wire _0334_;
  wire _0335_;
  wire _0336_;
  wire _0337_;
  wire _0338_;
  wire _0339_;
  wire _0340_;
  wire _0341_;
  wire _0342_;
  wire _0343_;
  wire _0344_;
  wire _0345_;
  wire _0346_;
  wire _0347_;
  wire _0348_;
  wire _0349_;
  wire _0350_;
  wire _0351_;
  wire _0352_;
  wire _0353_;
  wire _0354_;
  wire _0355_;
  wire _0356_;
  wire _0357_;
  wire _0358_;
  wire _0359_;
  wire _0360_;
  wire _0361_;
  (* src = "src/Mega/interface_unit.sv:65.17-65.35" *)
  wire [7:0] clause_rx_fifo_lbd;
  (* src = "src/Mega/interface_unit.sv:66.18-66.36" *)
  wire [63:0] clause_rx_fifo_ptr;
  (* src = "src/Mega/interface_unit.sv:64.11-64.31" *)
  wire clause_rx_fifo_valid;
  (* src = "src/Mega/interface_unit.sv:63.25-63.39" *)
  wire [31:0] diverge_rx_lit;
  (* src = "src/Mega/interface_unit.sv:62.11-62.27" *)
  wire diverge_rx_valid;
  (* src = "src/Mega/interface_unit.sv:53.17-53.32" *)
  wire [3:0] neighbor_status;
  INV_X1 _0362_ (
    .A(rx_pkt_w[78]),
    .ZN(_0237_)
  );
  INV_X1 _0363_ (
    .A(rx_pkt_n[79]),
    .ZN(_0238_)
  );
  INV_X1 _0364_ (
    .A(rx_pkt_s[79]),
    .ZN(_0239_)
  );
  INV_X1 _0365_ (
    .A(rx_pkt_e[79]),
    .ZN(_0240_)
  );
  INV_X1 _0366_ (
    .A(rx_valid_n),
    .ZN(_0241_)
  );
  INV_X1 _0367_ (
    .A(rx_valid_s),
    .ZN(_0242_)
  );
  INV_X1 _0368_ (
    .A(rx_valid_e),
    .ZN(_0243_)
  );
  INV_X1 _0369_ (
    .A(rx_valid_w),
    .ZN(_0244_)
  );
  INV_X1 _0370_ (
    .A(tx_ready_n),
    .ZN(_0245_)
  );
  INV_X1 _0371_ (
    .A(diverge_req),
    .ZN(_0246_)
  );
  INV_X1 _0372_ (
    .A(tx_ready_s),
    .ZN(_0247_)
  );
  INV_X1 _0373_ (
    .A(tx_ready_e),
    .ZN(_0248_)
  );
  INV_X1 _0374_ (
    .A(tx_ready_w),
    .ZN(_0249_)
  );
  INV_X1 _0375_ (
    .A(diverge_lit[0]),
    .ZN(_0250_)
  );
  INV_X1 _0376_ (
    .A(diverge_lit[1]),
    .ZN(_0251_)
  );
  INV_X1 _0377_ (
    .A(diverge_lit[2]),
    .ZN(_0252_)
  );
  INV_X1 _0378_ (
    .A(diverge_lit[3]),
    .ZN(_0253_)
  );
  INV_X1 _0379_ (
    .A(diverge_lit[4]),
    .ZN(_0254_)
  );
  INV_X1 _0380_ (
    .A(diverge_lit[5]),
    .ZN(_0255_)
  );
  INV_X1 _0381_ (
    .A(diverge_lit[6]),
    .ZN(_0256_)
  );
  INV_X1 _0382_ (
    .A(diverge_lit[7]),
    .ZN(_0257_)
  );
  INV_X1 _0383_ (
    .A(diverge_lit[8]),
    .ZN(_0258_)
  );
  INV_X1 _0384_ (
    .A(diverge_lit[9]),
    .ZN(_0259_)
  );
  INV_X1 _0385_ (
    .A(diverge_lit[10]),
    .ZN(_0260_)
  );
  INV_X1 _0386_ (
    .A(diverge_lit[11]),
    .ZN(_0261_)
  );
  INV_X1 _0387_ (
    .A(diverge_lit[12]),
    .ZN(_0262_)
  );
  INV_X1 _0388_ (
    .A(diverge_lit[13]),
    .ZN(_0263_)
  );
  INV_X1 _0389_ (
    .A(diverge_lit[14]),
    .ZN(_0264_)
  );
  INV_X1 _0390_ (
    .A(diverge_lit[15]),
    .ZN(_0265_)
  );
  INV_X1 _0391_ (
    .A(diverge_lit[16]),
    .ZN(_0266_)
  );
  INV_X1 _0392_ (
    .A(diverge_lit[17]),
    .ZN(_0267_)
  );
  INV_X1 _0393_ (
    .A(diverge_lit[18]),
    .ZN(_0268_)
  );
  INV_X1 _0394_ (
    .A(diverge_lit[19]),
    .ZN(_0269_)
  );
  INV_X1 _0395_ (
    .A(diverge_lit[20]),
    .ZN(_0270_)
  );
  INV_X1 _0396_ (
    .A(diverge_lit[21]),
    .ZN(_0271_)
  );
  INV_X1 _0397_ (
    .A(diverge_lit[22]),
    .ZN(_0272_)
  );
  INV_X1 _0398_ (
    .A(diverge_lit[23]),
    .ZN(_0273_)
  );
  INV_X1 _0399_ (
    .A(diverge_lit[24]),
    .ZN(_0274_)
  );
  INV_X1 _0400_ (
    .A(diverge_lit[25]),
    .ZN(_0275_)
  );
  INV_X1 _0401_ (
    .A(diverge_lit[26]),
    .ZN(_0276_)
  );
  INV_X1 _0402_ (
    .A(diverge_lit[27]),
    .ZN(_0277_)
  );
  INV_X1 _0403_ (
    .A(diverge_lit[28]),
    .ZN(_0278_)
  );
  INV_X1 _0404_ (
    .A(diverge_lit[29]),
    .ZN(_0279_)
  );
  INV_X1 _0405_ (
    .A(diverge_lit[30]),
    .ZN(_0280_)
  );
  INV_X1 _0406_ (
    .A(diverge_lit[31]),
    .ZN(_0281_)
  );
  INV_X1 _0407_ (
    .A(rx_pkt_n[14]),
    .ZN(_0282_)
  );
  INV_X1 _0408_ (
    .A(rx_pkt_n[15]),
    .ZN(_0283_)
  );
  INV_X1 _0409_ (
    .A(rx_pkt_n[16]),
    .ZN(_0284_)
  );
  INV_X1 _0410_ (
    .A(rx_pkt_n[17]),
    .ZN(_0285_)
  );
  INV_X1 _0411_ (
    .A(rx_pkt_n[18]),
    .ZN(_0286_)
  );
  INV_X1 _0412_ (
    .A(rx_pkt_n[19]),
    .ZN(_0287_)
  );
  INV_X1 _0413_ (
    .A(rx_pkt_n[20]),
    .ZN(_0288_)
  );
  INV_X1 _0414_ (
    .A(rx_pkt_n[21]),
    .ZN(_0289_)
  );
  INV_X1 _0415_ (
    .A(rx_pkt_n[22]),
    .ZN(_0290_)
  );
  INV_X1 _0416_ (
    .A(rx_pkt_n[23]),
    .ZN(_0291_)
  );
  INV_X1 _0417_ (
    .A(rx_pkt_n[24]),
    .ZN(_0292_)
  );
  INV_X1 _0418_ (
    .A(rx_pkt_n[25]),
    .ZN(_0293_)
  );
  INV_X1 _0419_ (
    .A(rx_pkt_n[26]),
    .ZN(_0294_)
  );
  INV_X1 _0420_ (
    .A(rx_pkt_n[27]),
    .ZN(_0295_)
  );
  INV_X1 _0421_ (
    .A(rx_pkt_n[28]),
    .ZN(_0296_)
  );
  INV_X1 _0422_ (
    .A(rx_pkt_n[29]),
    .ZN(_0297_)
  );
  INV_X1 _0423_ (
    .A(rx_pkt_n[30]),
    .ZN(_0298_)
  );
  INV_X1 _0424_ (
    .A(rx_pkt_n[31]),
    .ZN(_0299_)
  );
  INV_X1 _0425_ (
    .A(rx_pkt_n[32]),
    .ZN(_0300_)
  );
  INV_X1 _0426_ (
    .A(rx_pkt_n[33]),
    .ZN(_0301_)
  );
  INV_X1 _0427_ (
    .A(rx_pkt_n[34]),
    .ZN(_0302_)
  );
  INV_X1 _0428_ (
    .A(rx_pkt_n[35]),
    .ZN(_0303_)
  );
  INV_X1 _0429_ (
    .A(rx_pkt_n[36]),
    .ZN(_0304_)
  );
  INV_X1 _0430_ (
    .A(rx_pkt_n[37]),
    .ZN(_0305_)
  );
  INV_X1 _0431_ (
    .A(rx_pkt_n[38]),
    .ZN(_0306_)
  );
  INV_X1 _0432_ (
    .A(rx_pkt_n[39]),
    .ZN(_0307_)
  );
  INV_X1 _0433_ (
    .A(rx_pkt_n[40]),
    .ZN(_0308_)
  );
  INV_X1 _0434_ (
    .A(rx_pkt_n[41]),
    .ZN(_0309_)
  );
  INV_X1 _0435_ (
    .A(rx_pkt_n[42]),
    .ZN(_0310_)
  );
  INV_X1 _0436_ (
    .A(rx_pkt_n[43]),
    .ZN(_0311_)
  );
  INV_X1 _0437_ (
    .A(rx_pkt_n[44]),
    .ZN(_0312_)
  );
  INV_X1 _0438_ (
    .A(rx_pkt_n[45]),
    .ZN(_0313_)
  );
  AOI22_X1 _0439_ (
    .A1(diverge_target[3]),
    .A2(_0245_),
    .B1(_0249_),
    .B2(diverge_target[0]),
    .ZN(_0314_)
  );
  AOI221_X1 _0440_ (
    .A(_0246_),
    .B1(_0247_),
    .B2(diverge_target[2]),
    .C1(_0248_),
    .C2(diverge_target[1]),
    .ZN(_0315_)
  );
  AND2_X1 _0441_ (
    .A1(_0314_),
    .A2(_0315_),
    .ZN(diverge_ack)
  );
  NAND3_X1 _0442_ (
    .A1(tx_ready_e),
    .A2(tx_ready_w),
    .A3(clause_bcast_req),
    .ZN(_0316_)
  );
  NOR3_X1 _0443_ (
    .A1(_0245_),
    .A2(_0247_),
    .A3(_0316_),
    .ZN(clause_bcast_ack)
  );
  NAND2_X1 _0444_ (
    .A1(_0246_),
    .A2(clause_bcast_req),
    .ZN(_0317_)
  );
  INV_X1 _0445_ (
    .A(_0317_),
    .ZN(tx_pkt_e[78])
  );
  NAND2_X1 _0446_ (
    .A1(clause_ptr[0]),
    .A2(tx_pkt_e[78]),
    .ZN(_0318_)
  );
  NAND2_X1 _0447_ (
    .A1(diverge_target[0]),
    .A2(diverge_req),
    .ZN(_0319_)
  );
  OAI21_X1 _0448_ (
    .A(_0318_),
    .B1(_0319_),
    .B2(_0250_),
    .ZN(tx_pkt_w[14])
  );
  NAND2_X1 _0449_ (
    .A1(clause_ptr[1]),
    .A2(tx_pkt_e[78]),
    .ZN(_0320_)
  );
  OAI21_X1 _0450_ (
    .A(_0320_),
    .B1(_0319_),
    .B2(_0251_),
    .ZN(tx_pkt_w[15])
  );
  NAND2_X1 _0451_ (
    .A1(clause_ptr[2]),
    .A2(tx_pkt_e[78]),
    .ZN(_0321_)
  );
  OAI21_X1 _0452_ (
    .A(_0321_),
    .B1(_0319_),
    .B2(_0252_),
    .ZN(tx_pkt_w[16])
  );
  NAND2_X1 _0453_ (
    .A1(clause_ptr[3]),
    .A2(tx_pkt_e[78]),
    .ZN(_0322_)
  );
  OAI21_X1 _0454_ (
    .A(_0322_),
    .B1(_0319_),
    .B2(_0253_),
    .ZN(tx_pkt_w[17])
  );
  NAND2_X1 _0455_ (
    .A1(clause_ptr[4]),
    .A2(tx_pkt_e[78]),
    .ZN(_0323_)
  );
  OAI21_X1 _0456_ (
    .A(_0323_),
    .B1(_0319_),
    .B2(_0254_),
    .ZN(tx_pkt_w[18])
  );
  NAND2_X1 _0457_ (
    .A1(clause_ptr[5]),
    .A2(tx_pkt_e[78]),
    .ZN(_0324_)
  );
  OAI21_X1 _0458_ (
    .A(_0324_),
    .B1(_0319_),
    .B2(_0255_),
    .ZN(tx_pkt_w[19])
  );
  NAND2_X1 _0459_ (
    .A1(clause_ptr[6]),
    .A2(tx_pkt_e[78]),
    .ZN(_0325_)
  );
  OAI21_X1 _0460_ (
    .A(_0325_),
    .B1(_0319_),
    .B2(_0256_),
    .ZN(tx_pkt_w[20])
  );
  NAND2_X1 _0461_ (
    .A1(clause_ptr[7]),
    .A2(tx_pkt_e[78]),
    .ZN(_0326_)
  );
  OAI21_X1 _0462_ (
    .A(_0326_),
    .B1(_0319_),
    .B2(_0257_),
    .ZN(tx_pkt_w[21])
  );
  NAND2_X1 _0463_ (
    .A1(clause_ptr[8]),
    .A2(tx_pkt_e[78]),
    .ZN(_0327_)
  );
  OAI21_X1 _0464_ (
    .A(_0327_),
    .B1(_0319_),
    .B2(_0258_),
    .ZN(tx_pkt_w[22])
  );
  NAND2_X1 _0465_ (
    .A1(clause_ptr[9]),
    .A2(tx_pkt_e[78]),
    .ZN(_0328_)
  );
  OAI21_X1 _0466_ (
    .A(_0328_),
    .B1(_0319_),
    .B2(_0259_),
    .ZN(tx_pkt_w[23])
  );
  NAND2_X1 _0467_ (
    .A1(clause_ptr[10]),
    .A2(tx_pkt_e[78]),
    .ZN(_0329_)
  );
  OAI21_X1 _0468_ (
    .A(_0329_),
    .B1(_0319_),
    .B2(_0260_),
    .ZN(tx_pkt_w[24])
  );
  NAND2_X1 _0469_ (
    .A1(clause_ptr[11]),
    .A2(tx_pkt_e[78]),
    .ZN(_0330_)
  );
  OAI21_X1 _0470_ (
    .A(_0330_),
    .B1(_0319_),
    .B2(_0261_),
    .ZN(tx_pkt_w[25])
  );
  NAND2_X1 _0471_ (
    .A1(clause_ptr[12]),
    .A2(tx_pkt_e[78]),
    .ZN(_0331_)
  );
  OAI21_X1 _0472_ (
    .A(_0331_),
    .B1(_0319_),
    .B2(_0262_),
    .ZN(tx_pkt_w[26])
  );
  NAND2_X1 _0473_ (
    .A1(clause_ptr[13]),
    .A2(tx_pkt_e[78]),
    .ZN(_0332_)
  );
  OAI21_X1 _0474_ (
    .A(_0332_),
    .B1(_0319_),
    .B2(_0263_),
    .ZN(tx_pkt_w[27])
  );
  NAND2_X1 _0475_ (
    .A1(clause_ptr[14]),
    .A2(tx_pkt_e[78]),
    .ZN(_0333_)
  );
  OAI21_X1 _0476_ (
    .A(_0333_),
    .B1(_0319_),
    .B2(_0264_),
    .ZN(tx_pkt_w[28])
  );
  NAND2_X1 _0477_ (
    .A1(clause_ptr[15]),
    .A2(tx_pkt_e[78]),
    .ZN(_0334_)
  );
  OAI21_X1 _0478_ (
    .A(_0334_),
    .B1(_0319_),
    .B2(_0265_),
    .ZN(tx_pkt_w[29])
  );
  NAND2_X1 _0479_ (
    .A1(clause_ptr[16]),
    .A2(tx_pkt_e[78]),
    .ZN(_0335_)
  );
  OAI21_X1 _0480_ (
    .A(_0335_),
    .B1(_0319_),
    .B2(_0266_),
    .ZN(tx_pkt_w[30])
  );
  NAND2_X1 _0481_ (
    .A1(clause_ptr[17]),
    .A2(tx_pkt_e[78]),
    .ZN(_0336_)
  );
  OAI21_X1 _0482_ (
    .A(_0336_),
    .B1(_0319_),
    .B2(_0267_),
    .ZN(tx_pkt_w[31])
  );
  NAND2_X1 _0483_ (
    .A1(clause_ptr[18]),
    .A2(tx_pkt_e[78]),
    .ZN(_0337_)
  );
  OAI21_X1 _0484_ (
    .A(_0337_),
    .B1(_0319_),
    .B2(_0268_),
    .ZN(tx_pkt_w[32])
  );
  NAND2_X1 _0485_ (
    .A1(clause_ptr[19]),
    .A2(tx_pkt_e[78]),
    .ZN(_0338_)
  );
  OAI21_X1 _0486_ (
    .A(_0338_),
    .B1(_0319_),
    .B2(_0269_),
    .ZN(tx_pkt_w[33])
  );
  NAND2_X1 _0487_ (
    .A1(clause_ptr[20]),
    .A2(tx_pkt_e[78]),
    .ZN(_0339_)
  );
  OAI21_X1 _0488_ (
    .A(_0339_),
    .B1(_0319_),
    .B2(_0270_),
    .ZN(tx_pkt_w[34])
  );
  NAND2_X1 _0489_ (
    .A1(clause_ptr[21]),
    .A2(tx_pkt_e[78]),
    .ZN(_0340_)
  );
  OAI21_X1 _0490_ (
    .A(_0340_),
    .B1(_0319_),
    .B2(_0271_),
    .ZN(tx_pkt_w[35])
  );
  NAND2_X1 _0491_ (
    .A1(clause_ptr[22]),
    .A2(tx_pkt_e[78]),
    .ZN(_0341_)
  );
  OAI21_X1 _0492_ (
    .A(_0341_),
    .B1(_0319_),
    .B2(_0272_),
    .ZN(tx_pkt_w[36])
  );
  NAND2_X1 _0493_ (
    .A1(clause_ptr[23]),
    .A2(tx_pkt_e[78]),
    .ZN(_0342_)
  );
  OAI21_X1 _0494_ (
    .A(_0342_),
    .B1(_0319_),
    .B2(_0273_),
    .ZN(tx_pkt_w[37])
  );
  NAND2_X1 _0495_ (
    .A1(clause_ptr[24]),
    .A2(tx_pkt_e[78]),
    .ZN(_0343_)
  );
  OAI21_X1 _0496_ (
    .A(_0343_),
    .B1(_0319_),
    .B2(_0274_),
    .ZN(tx_pkt_w[38])
  );
  NAND2_X1 _0497_ (
    .A1(clause_ptr[25]),
    .A2(tx_pkt_e[78]),
    .ZN(_0344_)
  );
  OAI21_X1 _0498_ (
    .A(_0344_),
    .B1(_0319_),
    .B2(_0275_),
    .ZN(tx_pkt_w[39])
  );
  NAND2_X1 _0499_ (
    .A1(clause_ptr[26]),
    .A2(tx_pkt_e[78]),
    .ZN(_0345_)
  );
  OAI21_X1 _0500_ (
    .A(_0345_),
    .B1(_0319_),
    .B2(_0276_),
    .ZN(tx_pkt_w[40])
  );
  NAND2_X1 _0501_ (
    .A1(clause_ptr[27]),
    .A2(tx_pkt_e[78]),
    .ZN(_0346_)
  );
  OAI21_X1 _0502_ (
    .A(_0346_),
    .B1(_0319_),
    .B2(_0277_),
    .ZN(tx_pkt_w[41])
  );
  NAND2_X1 _0503_ (
    .A1(clause_ptr[28]),
    .A2(tx_pkt_e[78]),
    .ZN(_0347_)
  );
  OAI21_X1 _0504_ (
    .A(_0347_),
    .B1(_0319_),
    .B2(_0278_),
    .ZN(tx_pkt_w[42])
  );
  NAND2_X1 _0505_ (
    .A1(clause_ptr[29]),
    .A2(tx_pkt_e[78]),
    .ZN(_0348_)
  );
  OAI21_X1 _0506_ (
    .A(_0348_),
    .B1(_0319_),
    .B2(_0279_),
    .ZN(tx_pkt_w[43])
  );
  NAND2_X1 _0507_ (
    .A1(clause_ptr[30]),
    .A2(tx_pkt_e[78]),
    .ZN(_0349_)
  );
  OAI21_X1 _0508_ (
    .A(_0349_),
    .B1(_0319_),
    .B2(_0280_),
    .ZN(tx_pkt_w[44])
  );
  NAND2_X1 _0509_ (
    .A1(clause_ptr[31]),
    .A2(tx_pkt_e[78]),
    .ZN(_0350_)
  );
  OAI21_X1 _0510_ (
    .A(_0350_),
    .B1(_0319_),
    .B2(_0281_),
    .ZN(tx_pkt_w[45])
  );
  NAND2_X1 _0511_ (
    .A1(_0317_),
    .A2(_0319_),
    .ZN(tx_valid_w)
  );
  NAND2_X1 _0512_ (
    .A1(diverge_target[1]),
    .A2(diverge_req),
    .ZN(_0351_)
  );
  OAI21_X1 _0513_ (
    .A(_0318_),
    .B1(_0351_),
    .B2(_0250_),
    .ZN(tx_pkt_e[14])
  );
  OAI21_X1 _0514_ (
    .A(_0320_),
    .B1(_0351_),
    .B2(_0251_),
    .ZN(tx_pkt_e[15])
  );
  OAI21_X1 _0515_ (
    .A(_0321_),
    .B1(_0351_),
    .B2(_0252_),
    .ZN(tx_pkt_e[16])
  );
  OAI21_X1 _0516_ (
    .A(_0322_),
    .B1(_0351_),
    .B2(_0253_),
    .ZN(tx_pkt_e[17])
  );
  OAI21_X1 _0517_ (
    .A(_0323_),
    .B1(_0351_),
    .B2(_0254_),
    .ZN(tx_pkt_e[18])
  );
  OAI21_X1 _0518_ (
    .A(_0324_),
    .B1(_0351_),
    .B2(_0255_),
    .ZN(tx_pkt_e[19])
  );
  OAI21_X1 _0519_ (
    .A(_0325_),
    .B1(_0351_),
    .B2(_0256_),
    .ZN(tx_pkt_e[20])
  );
  OAI21_X1 _0520_ (
    .A(_0326_),
    .B1(_0351_),
    .B2(_0257_),
    .ZN(tx_pkt_e[21])
  );
  OAI21_X1 _0521_ (
    .A(_0327_),
    .B1(_0351_),
    .B2(_0258_),
    .ZN(tx_pkt_e[22])
  );
  OAI21_X1 _0522_ (
    .A(_0328_),
    .B1(_0351_),
    .B2(_0259_),
    .ZN(tx_pkt_e[23])
  );
  OAI21_X1 _0523_ (
    .A(_0329_),
    .B1(_0351_),
    .B2(_0260_),
    .ZN(tx_pkt_e[24])
  );
  OAI21_X1 _0524_ (
    .A(_0330_),
    .B1(_0351_),
    .B2(_0261_),
    .ZN(tx_pkt_e[25])
  );
  OAI21_X1 _0525_ (
    .A(_0331_),
    .B1(_0351_),
    .B2(_0262_),
    .ZN(tx_pkt_e[26])
  );
  OAI21_X1 _0526_ (
    .A(_0332_),
    .B1(_0351_),
    .B2(_0263_),
    .ZN(tx_pkt_e[27])
  );
  OAI21_X1 _0527_ (
    .A(_0333_),
    .B1(_0351_),
    .B2(_0264_),
    .ZN(tx_pkt_e[28])
  );
  OAI21_X1 _0528_ (
    .A(_0334_),
    .B1(_0351_),
    .B2(_0265_),
    .ZN(tx_pkt_e[29])
  );
  OAI21_X1 _0529_ (
    .A(_0335_),
    .B1(_0351_),
    .B2(_0266_),
    .ZN(tx_pkt_e[30])
  );
  OAI21_X1 _0530_ (
    .A(_0336_),
    .B1(_0351_),
    .B2(_0267_),
    .ZN(tx_pkt_e[31])
  );
  OAI21_X1 _0531_ (
    .A(_0337_),
    .B1(_0351_),
    .B2(_0268_),
    .ZN(tx_pkt_e[32])
  );
  OAI21_X1 _0532_ (
    .A(_0338_),
    .B1(_0351_),
    .B2(_0269_),
    .ZN(tx_pkt_e[33])
  );
  OAI21_X1 _0533_ (
    .A(_0339_),
    .B1(_0351_),
    .B2(_0270_),
    .ZN(tx_pkt_e[34])
  );
  OAI21_X1 _0534_ (
    .A(_0340_),
    .B1(_0351_),
    .B2(_0271_),
    .ZN(tx_pkt_e[35])
  );
  OAI21_X1 _0535_ (
    .A(_0341_),
    .B1(_0351_),
    .B2(_0272_),
    .ZN(tx_pkt_e[36])
  );
  OAI21_X1 _0536_ (
    .A(_0342_),
    .B1(_0351_),
    .B2(_0273_),
    .ZN(tx_pkt_e[37])
  );
  OAI21_X1 _0537_ (
    .A(_0343_),
    .B1(_0351_),
    .B2(_0274_),
    .ZN(tx_pkt_e[38])
  );
  OAI21_X1 _0538_ (
    .A(_0344_),
    .B1(_0351_),
    .B2(_0275_),
    .ZN(tx_pkt_e[39])
  );
  OAI21_X1 _0539_ (
    .A(_0345_),
    .B1(_0351_),
    .B2(_0276_),
    .ZN(tx_pkt_e[40])
  );
  OAI21_X1 _0540_ (
    .A(_0346_),
    .B1(_0351_),
    .B2(_0277_),
    .ZN(tx_pkt_e[41])
  );
  OAI21_X1 _0541_ (
    .A(_0347_),
    .B1(_0351_),
    .B2(_0278_),
    .ZN(tx_pkt_e[42])
  );
  OAI21_X1 _0542_ (
    .A(_0348_),
    .B1(_0351_),
    .B2(_0279_),
    .ZN(tx_pkt_e[43])
  );
  OAI21_X1 _0543_ (
    .A(_0349_),
    .B1(_0351_),
    .B2(_0280_),
    .ZN(tx_pkt_e[44])
  );
  OAI21_X1 _0544_ (
    .A(_0350_),
    .B1(_0351_),
    .B2(_0281_),
    .ZN(tx_pkt_e[45])
  );
  NAND2_X1 _0545_ (
    .A1(_0317_),
    .A2(_0351_),
    .ZN(tx_valid_e)
  );
  NAND2_X1 _0546_ (
    .A1(diverge_target[2]),
    .A2(diverge_req),
    .ZN(_0352_)
  );
  OAI21_X1 _0547_ (
    .A(_0318_),
    .B1(_0352_),
    .B2(_0250_),
    .ZN(tx_pkt_s[14])
  );
  OAI21_X1 _0548_ (
    .A(_0320_),
    .B1(_0352_),
    .B2(_0251_),
    .ZN(tx_pkt_s[15])
  );
  OAI21_X1 _0549_ (
    .A(_0321_),
    .B1(_0352_),
    .B2(_0252_),
    .ZN(tx_pkt_s[16])
  );
  OAI21_X1 _0550_ (
    .A(_0322_),
    .B1(_0352_),
    .B2(_0253_),
    .ZN(tx_pkt_s[17])
  );
  OAI21_X1 _0551_ (
    .A(_0323_),
    .B1(_0352_),
    .B2(_0254_),
    .ZN(tx_pkt_s[18])
  );
  OAI21_X1 _0552_ (
    .A(_0324_),
    .B1(_0352_),
    .B2(_0255_),
    .ZN(tx_pkt_s[19])
  );
  OAI21_X1 _0553_ (
    .A(_0325_),
    .B1(_0352_),
    .B2(_0256_),
    .ZN(tx_pkt_s[20])
  );
  OAI21_X1 _0554_ (
    .A(_0326_),
    .B1(_0352_),
    .B2(_0257_),
    .ZN(tx_pkt_s[21])
  );
  OAI21_X1 _0555_ (
    .A(_0327_),
    .B1(_0352_),
    .B2(_0258_),
    .ZN(tx_pkt_s[22])
  );
  OAI21_X1 _0556_ (
    .A(_0328_),
    .B1(_0352_),
    .B2(_0259_),
    .ZN(tx_pkt_s[23])
  );
  OAI21_X1 _0557_ (
    .A(_0329_),
    .B1(_0352_),
    .B2(_0260_),
    .ZN(tx_pkt_s[24])
  );
  OAI21_X1 _0558_ (
    .A(_0330_),
    .B1(_0352_),
    .B2(_0261_),
    .ZN(tx_pkt_s[25])
  );
  OAI21_X1 _0559_ (
    .A(_0331_),
    .B1(_0352_),
    .B2(_0262_),
    .ZN(tx_pkt_s[26])
  );
  OAI21_X1 _0560_ (
    .A(_0332_),
    .B1(_0352_),
    .B2(_0263_),
    .ZN(tx_pkt_s[27])
  );
  OAI21_X1 _0561_ (
    .A(_0333_),
    .B1(_0352_),
    .B2(_0264_),
    .ZN(tx_pkt_s[28])
  );
  OAI21_X1 _0562_ (
    .A(_0334_),
    .B1(_0352_),
    .B2(_0265_),
    .ZN(tx_pkt_s[29])
  );
  OAI21_X1 _0563_ (
    .A(_0335_),
    .B1(_0352_),
    .B2(_0266_),
    .ZN(tx_pkt_s[30])
  );
  OAI21_X1 _0564_ (
    .A(_0336_),
    .B1(_0352_),
    .B2(_0267_),
    .ZN(tx_pkt_s[31])
  );
  OAI21_X1 _0565_ (
    .A(_0337_),
    .B1(_0352_),
    .B2(_0268_),
    .ZN(tx_pkt_s[32])
  );
  OAI21_X1 _0566_ (
    .A(_0338_),
    .B1(_0352_),
    .B2(_0269_),
    .ZN(tx_pkt_s[33])
  );
  OAI21_X1 _0567_ (
    .A(_0339_),
    .B1(_0352_),
    .B2(_0270_),
    .ZN(tx_pkt_s[34])
  );
  OAI21_X1 _0568_ (
    .A(_0340_),
    .B1(_0352_),
    .B2(_0271_),
    .ZN(tx_pkt_s[35])
  );
  OAI21_X1 _0569_ (
    .A(_0341_),
    .B1(_0352_),
    .B2(_0272_),
    .ZN(tx_pkt_s[36])
  );
  OAI21_X1 _0570_ (
    .A(_0342_),
    .B1(_0352_),
    .B2(_0273_),
    .ZN(tx_pkt_s[37])
  );
  OAI21_X1 _0571_ (
    .A(_0343_),
    .B1(_0352_),
    .B2(_0274_),
    .ZN(tx_pkt_s[38])
  );
  OAI21_X1 _0572_ (
    .A(_0344_),
    .B1(_0352_),
    .B2(_0275_),
    .ZN(tx_pkt_s[39])
  );
  OAI21_X1 _0573_ (
    .A(_0345_),
    .B1(_0352_),
    .B2(_0276_),
    .ZN(tx_pkt_s[40])
  );
  OAI21_X1 _0574_ (
    .A(_0346_),
    .B1(_0352_),
    .B2(_0277_),
    .ZN(tx_pkt_s[41])
  );
  OAI21_X1 _0575_ (
    .A(_0347_),
    .B1(_0352_),
    .B2(_0278_),
    .ZN(tx_pkt_s[42])
  );
  OAI21_X1 _0576_ (
    .A(_0348_),
    .B1(_0352_),
    .B2(_0279_),
    .ZN(tx_pkt_s[43])
  );
  OAI21_X1 _0577_ (
    .A(_0349_),
    .B1(_0352_),
    .B2(_0280_),
    .ZN(tx_pkt_s[44])
  );
  OAI21_X1 _0578_ (
    .A(_0350_),
    .B1(_0352_),
    .B2(_0281_),
    .ZN(tx_pkt_s[45])
  );
  NAND2_X1 _0579_ (
    .A1(_0317_),
    .A2(_0352_),
    .ZN(tx_valid_s)
  );
  NAND2_X1 _0580_ (
    .A1(diverge_target[3]),
    .A2(diverge_req),
    .ZN(_0353_)
  );
  OAI21_X1 _0581_ (
    .A(_0318_),
    .B1(_0353_),
    .B2(_0250_),
    .ZN(tx_pkt_n[14])
  );
  OAI21_X1 _0582_ (
    .A(_0320_),
    .B1(_0353_),
    .B2(_0251_),
    .ZN(tx_pkt_n[15])
  );
  OAI21_X1 _0583_ (
    .A(_0321_),
    .B1(_0353_),
    .B2(_0252_),
    .ZN(tx_pkt_n[16])
  );
  OAI21_X1 _0584_ (
    .A(_0322_),
    .B1(_0353_),
    .B2(_0253_),
    .ZN(tx_pkt_n[17])
  );
  OAI21_X1 _0585_ (
    .A(_0323_),
    .B1(_0353_),
    .B2(_0254_),
    .ZN(tx_pkt_n[18])
  );
  OAI21_X1 _0586_ (
    .A(_0324_),
    .B1(_0353_),
    .B2(_0255_),
    .ZN(tx_pkt_n[19])
  );
  OAI21_X1 _0587_ (
    .A(_0325_),
    .B1(_0353_),
    .B2(_0256_),
    .ZN(tx_pkt_n[20])
  );
  OAI21_X1 _0588_ (
    .A(_0326_),
    .B1(_0353_),
    .B2(_0257_),
    .ZN(tx_pkt_n[21])
  );
  OAI21_X1 _0589_ (
    .A(_0327_),
    .B1(_0353_),
    .B2(_0258_),
    .ZN(tx_pkt_n[22])
  );
  OAI21_X1 _0590_ (
    .A(_0328_),
    .B1(_0353_),
    .B2(_0259_),
    .ZN(tx_pkt_n[23])
  );
  OAI21_X1 _0591_ (
    .A(_0329_),
    .B1(_0353_),
    .B2(_0260_),
    .ZN(tx_pkt_n[24])
  );
  OAI21_X1 _0592_ (
    .A(_0330_),
    .B1(_0353_),
    .B2(_0261_),
    .ZN(tx_pkt_n[25])
  );
  OAI21_X1 _0593_ (
    .A(_0331_),
    .B1(_0353_),
    .B2(_0262_),
    .ZN(tx_pkt_n[26])
  );
  OAI21_X1 _0594_ (
    .A(_0332_),
    .B1(_0353_),
    .B2(_0263_),
    .ZN(tx_pkt_n[27])
  );
  OAI21_X1 _0595_ (
    .A(_0333_),
    .B1(_0353_),
    .B2(_0264_),
    .ZN(tx_pkt_n[28])
  );
  OAI21_X1 _0596_ (
    .A(_0334_),
    .B1(_0353_),
    .B2(_0265_),
    .ZN(tx_pkt_n[29])
  );
  OAI21_X1 _0597_ (
    .A(_0335_),
    .B1(_0353_),
    .B2(_0266_),
    .ZN(tx_pkt_n[30])
  );
  OAI21_X1 _0598_ (
    .A(_0336_),
    .B1(_0353_),
    .B2(_0267_),
    .ZN(tx_pkt_n[31])
  );
  OAI21_X1 _0599_ (
    .A(_0337_),
    .B1(_0353_),
    .B2(_0268_),
    .ZN(tx_pkt_n[32])
  );
  OAI21_X1 _0600_ (
    .A(_0338_),
    .B1(_0353_),
    .B2(_0269_),
    .ZN(tx_pkt_n[33])
  );
  OAI21_X1 _0601_ (
    .A(_0339_),
    .B1(_0353_),
    .B2(_0270_),
    .ZN(tx_pkt_n[34])
  );
  OAI21_X1 _0602_ (
    .A(_0340_),
    .B1(_0353_),
    .B2(_0271_),
    .ZN(tx_pkt_n[35])
  );
  OAI21_X1 _0603_ (
    .A(_0341_),
    .B1(_0353_),
    .B2(_0272_),
    .ZN(tx_pkt_n[36])
  );
  OAI21_X1 _0604_ (
    .A(_0342_),
    .B1(_0353_),
    .B2(_0273_),
    .ZN(tx_pkt_n[37])
  );
  OAI21_X1 _0605_ (
    .A(_0343_),
    .B1(_0353_),
    .B2(_0274_),
    .ZN(tx_pkt_n[38])
  );
  OAI21_X1 _0606_ (
    .A(_0344_),
    .B1(_0353_),
    .B2(_0275_),
    .ZN(tx_pkt_n[39])
  );
  OAI21_X1 _0607_ (
    .A(_0345_),
    .B1(_0353_),
    .B2(_0276_),
    .ZN(tx_pkt_n[40])
  );
  OAI21_X1 _0608_ (
    .A(_0346_),
    .B1(_0353_),
    .B2(_0277_),
    .ZN(tx_pkt_n[41])
  );
  OAI21_X1 _0609_ (
    .A(_0347_),
    .B1(_0353_),
    .B2(_0278_),
    .ZN(tx_pkt_n[42])
  );
  OAI21_X1 _0610_ (
    .A(_0348_),
    .B1(_0353_),
    .B2(_0279_),
    .ZN(tx_pkt_n[43])
  );
  OAI21_X1 _0611_ (
    .A(_0349_),
    .B1(_0353_),
    .B2(_0280_),
    .ZN(tx_pkt_n[44])
  );
  OAI21_X1 _0612_ (
    .A(_0350_),
    .B1(_0353_),
    .B2(_0281_),
    .ZN(tx_pkt_n[45])
  );
  AND2_X1 _0613_ (
    .A1(clause_ptr[32]),
    .A2(tx_pkt_e[78]),
    .ZN(tx_pkt_e[46])
  );
  AND2_X1 _0614_ (
    .A1(clause_ptr[33]),
    .A2(tx_pkt_e[78]),
    .ZN(tx_pkt_e[47])
  );
  AND2_X1 _0615_ (
    .A1(clause_ptr[34]),
    .A2(tx_pkt_e[78]),
    .ZN(tx_pkt_e[48])
  );
  AND2_X1 _0616_ (
    .A1(clause_ptr[35]),
    .A2(tx_pkt_e[78]),
    .ZN(tx_pkt_e[49])
  );
  AND2_X1 _0617_ (
    .A1(clause_ptr[36]),
    .A2(tx_pkt_e[78]),
    .ZN(tx_pkt_e[50])
  );
  AND2_X1 _0618_ (
    .A1(clause_ptr[37]),
    .A2(tx_pkt_e[78]),
    .ZN(tx_pkt_e[51])
  );
  AND2_X1 _0619_ (
    .A1(clause_ptr[38]),
    .A2(tx_pkt_e[78]),
    .ZN(tx_pkt_e[52])
  );
  AND2_X1 _0620_ (
    .A1(clause_ptr[39]),
    .A2(tx_pkt_e[78]),
    .ZN(tx_pkt_e[53])
  );
  AND2_X1 _0621_ (
    .A1(clause_ptr[40]),
    .A2(tx_pkt_e[78]),
    .ZN(tx_pkt_e[54])
  );
  AND2_X1 _0622_ (
    .A1(clause_ptr[41]),
    .A2(tx_pkt_e[78]),
    .ZN(tx_pkt_e[55])
  );
  AND2_X1 _0623_ (
    .A1(clause_ptr[42]),
    .A2(tx_pkt_e[78]),
    .ZN(tx_pkt_e[56])
  );
  AND2_X1 _0624_ (
    .A1(clause_ptr[43]),
    .A2(tx_pkt_e[78]),
    .ZN(tx_pkt_e[57])
  );
  AND2_X1 _0625_ (
    .A1(clause_ptr[44]),
    .A2(tx_pkt_e[78]),
    .ZN(tx_pkt_e[58])
  );
  AND2_X1 _0626_ (
    .A1(clause_ptr[45]),
    .A2(tx_pkt_e[78]),
    .ZN(tx_pkt_e[59])
  );
  AND2_X1 _0627_ (
    .A1(clause_ptr[46]),
    .A2(tx_pkt_e[78]),
    .ZN(tx_pkt_e[60])
  );
  AND2_X1 _0628_ (
    .A1(clause_ptr[47]),
    .A2(tx_pkt_e[78]),
    .ZN(tx_pkt_e[61])
  );
  AND2_X1 _0629_ (
    .A1(clause_ptr[48]),
    .A2(tx_pkt_e[78]),
    .ZN(tx_pkt_e[62])
  );
  AND2_X1 _0630_ (
    .A1(clause_ptr[49]),
    .A2(tx_pkt_e[78]),
    .ZN(tx_pkt_e[63])
  );
  AND2_X1 _0631_ (
    .A1(clause_ptr[50]),
    .A2(tx_pkt_e[78]),
    .ZN(tx_pkt_e[64])
  );
  AND2_X1 _0632_ (
    .A1(clause_ptr[51]),
    .A2(tx_pkt_e[78]),
    .ZN(tx_pkt_e[65])
  );
  AND2_X1 _0633_ (
    .A1(clause_ptr[52]),
    .A2(tx_pkt_e[78]),
    .ZN(tx_pkt_e[66])
  );
  AND2_X1 _0634_ (
    .A1(clause_ptr[53]),
    .A2(tx_pkt_e[78]),
    .ZN(tx_pkt_e[67])
  );
  AND2_X1 _0635_ (
    .A1(clause_ptr[54]),
    .A2(tx_pkt_e[78]),
    .ZN(tx_pkt_e[68])
  );
  AND2_X1 _0636_ (
    .A1(clause_ptr[55]),
    .A2(tx_pkt_e[78]),
    .ZN(tx_pkt_e[69])
  );
  AND2_X1 _0637_ (
    .A1(clause_ptr[56]),
    .A2(tx_pkt_e[78]),
    .ZN(tx_pkt_e[70])
  );
  AND2_X1 _0638_ (
    .A1(clause_ptr[57]),
    .A2(tx_pkt_e[78]),
    .ZN(tx_pkt_e[71])
  );
  AND2_X1 _0639_ (
    .A1(clause_ptr[58]),
    .A2(tx_pkt_e[78]),
    .ZN(tx_pkt_e[72])
  );
  AND2_X1 _0640_ (
    .A1(clause_ptr[59]),
    .A2(tx_pkt_e[78]),
    .ZN(tx_pkt_e[73])
  );
  AND2_X1 _0641_ (
    .A1(clause_ptr[60]),
    .A2(tx_pkt_e[78]),
    .ZN(tx_pkt_e[74])
  );
  AND2_X1 _0642_ (
    .A1(clause_ptr[61]),
    .A2(tx_pkt_e[78]),
    .ZN(tx_pkt_e[75])
  );
  AND2_X1 _0643_ (
    .A1(clause_ptr[62]),
    .A2(tx_pkt_e[78]),
    .ZN(tx_pkt_e[76])
  );
  AND2_X1 _0644_ (
    .A1(clause_ptr[63]),
    .A2(tx_pkt_e[78]),
    .ZN(tx_pkt_e[77])
  );
  NAND2_X1 _0645_ (
    .A1(_0317_),
    .A2(_0353_),
    .ZN(tx_valid_n)
  );
  AND2_X1 _0646_ (
    .A1(clause_lbd[0]),
    .A2(tx_pkt_e[78]),
    .ZN(tx_pkt_e[6])
  );
  AND2_X1 _0647_ (
    .A1(clause_lbd[1]),
    .A2(tx_pkt_e[78]),
    .ZN(tx_pkt_e[7])
  );
  AND2_X1 _0648_ (
    .A1(clause_lbd[2]),
    .A2(tx_pkt_e[78]),
    .ZN(tx_pkt_e[8])
  );
  AND2_X1 _0649_ (
    .A1(clause_lbd[3]),
    .A2(tx_pkt_e[78]),
    .ZN(tx_pkt_e[9])
  );
  AND2_X1 _0650_ (
    .A1(clause_lbd[4]),
    .A2(tx_pkt_e[78]),
    .ZN(tx_pkt_e[10])
  );
  AND2_X1 _0651_ (
    .A1(clause_lbd[5]),
    .A2(tx_pkt_e[78]),
    .ZN(tx_pkt_e[11])
  );
  AND2_X1 _0652_ (
    .A1(clause_lbd[6]),
    .A2(tx_pkt_e[78]),
    .ZN(tx_pkt_e[12])
  );
  AND2_X1 _0653_ (
    .A1(clause_lbd[7]),
    .A2(tx_pkt_e[78]),
    .ZN(tx_pkt_e[13])
  );
  NAND2_X1 _0654_ (
    .A1(_0238_),
    .A2(rx_valid_n),
    .ZN(_0354_)
  );
  NOR2_X1 _0655_ (
    .A1(rx_pkt_n[78]),
    .A2(_0354_),
    .ZN(_0355_)
  );
  OR3_X1 _0656_ (
    .A1(rx_pkt_s[78]),
    .A2(rx_pkt_s[79]),
    .A3(_0242_),
    .ZN(_0356_)
  );
  INV_X1 _0657_ (
    .A(_0356_),
    .ZN(_0357_)
  );
  NOR2_X1 _0658_ (
    .A1(rx_pkt_w[79]),
    .A2(_0244_),
    .ZN(_0358_)
  );
  OR2_X1 _0659_ (
    .A1(rx_pkt_w[79]),
    .A2(_0244_),
    .ZN(_0359_)
  );
  NOR3_X1 _0660_ (
    .A1(rx_pkt_w[78]),
    .A2(rx_pkt_w[79]),
    .A3(_0244_),
    .ZN(_0360_)
  );
  NOR3_X1 _0661_ (
    .A1(rx_pkt_e[78]),
    .A2(rx_pkt_e[79]),
    .A3(_0243_),
    .ZN(_0361_)
  );
  OR3_X1 _0662_ (
    .A1(rx_pkt_e[78]),
    .A2(rx_pkt_e[79]),
    .A3(_0243_),
    .ZN(_0000_)
  );
  NOR4_X1 _0663_ (
    .A1(_0354_),
    .A2(_0357_),
    .A3(_0360_),
    .A4(_0361_),
    .ZN(_0001_)
  );
  OR2_X1 _0664_ (
    .A1(_0355_),
    .A2(_0001_),
    .ZN(rx_ready_n)
  );
  OAI33_X1 _0665_ (
    .A1(rx_pkt_n[78]),
    .A2(rx_pkt_n[79]),
    .A3(_0241_),
    .B1(_0242_),
    .B2(rx_pkt_s[79]),
    .B3(rx_pkt_s[78]),
    .ZN(_0002_)
  );
  AND2_X1 _0666_ (
    .A1(_0360_),
    .A2(_0000_),
    .ZN(_0003_)
  );
  AOI221_X1 _0667_ (
    .A(_0002_),
    .B1(_0003_),
    .B2(rx_pkt_w[14]),
    .C1(rx_pkt_e[14]),
    .C2(_0361_),
    .ZN(_0004_)
  );
  NOR3_X1 _0668_ (
    .A1(rx_pkt_s[14]),
    .A2(_0355_),
    .A3(_0356_),
    .ZN(_0005_)
  );
  AOI211_X1 _0669_ (
    .A(_0004_),
    .B(_0005_),
    .C1(_0282_),
    .C2(_0355_),
    .ZN(force_lit[0])
  );
  AOI221_X1 _0670_ (
    .A(_0002_),
    .B1(_0003_),
    .B2(rx_pkt_w[15]),
    .C1(rx_pkt_e[15]),
    .C2(_0361_),
    .ZN(_0006_)
  );
  NOR3_X1 _0671_ (
    .A1(rx_pkt_s[15]),
    .A2(_0355_),
    .A3(_0356_),
    .ZN(_0007_)
  );
  AOI211_X1 _0672_ (
    .A(_0006_),
    .B(_0007_),
    .C1(_0283_),
    .C2(_0355_),
    .ZN(force_lit[1])
  );
  AOI221_X1 _0673_ (
    .A(_0002_),
    .B1(_0003_),
    .B2(rx_pkt_w[16]),
    .C1(rx_pkt_e[16]),
    .C2(_0361_),
    .ZN(_0008_)
  );
  NOR3_X1 _0674_ (
    .A1(rx_pkt_s[16]),
    .A2(_0355_),
    .A3(_0356_),
    .ZN(_0009_)
  );
  AOI211_X1 _0675_ (
    .A(_0008_),
    .B(_0009_),
    .C1(_0284_),
    .C2(_0355_),
    .ZN(force_lit[2])
  );
  AOI221_X1 _0676_ (
    .A(_0002_),
    .B1(_0003_),
    .B2(rx_pkt_w[17]),
    .C1(rx_pkt_e[17]),
    .C2(_0361_),
    .ZN(_0010_)
  );
  NOR3_X1 _0677_ (
    .A1(rx_pkt_s[17]),
    .A2(_0355_),
    .A3(_0356_),
    .ZN(_0011_)
  );
  AOI211_X1 _0678_ (
    .A(_0010_),
    .B(_0011_),
    .C1(_0285_),
    .C2(_0355_),
    .ZN(force_lit[3])
  );
  AOI221_X1 _0679_ (
    .A(_0002_),
    .B1(_0003_),
    .B2(rx_pkt_w[18]),
    .C1(rx_pkt_e[18]),
    .C2(_0361_),
    .ZN(_0012_)
  );
  NOR3_X1 _0680_ (
    .A1(rx_pkt_s[18]),
    .A2(_0355_),
    .A3(_0356_),
    .ZN(_0013_)
  );
  AOI211_X1 _0681_ (
    .A(_0012_),
    .B(_0013_),
    .C1(_0286_),
    .C2(_0355_),
    .ZN(force_lit[4])
  );
  AOI221_X1 _0682_ (
    .A(_0002_),
    .B1(_0003_),
    .B2(rx_pkt_w[19]),
    .C1(rx_pkt_e[19]),
    .C2(_0361_),
    .ZN(_0014_)
  );
  NOR3_X1 _0683_ (
    .A1(rx_pkt_s[19]),
    .A2(_0355_),
    .A3(_0356_),
    .ZN(_0015_)
  );
  AOI211_X1 _0684_ (
    .A(_0014_),
    .B(_0015_),
    .C1(_0287_),
    .C2(_0355_),
    .ZN(force_lit[5])
  );
  AOI221_X1 _0685_ (
    .A(_0002_),
    .B1(_0003_),
    .B2(rx_pkt_w[20]),
    .C1(rx_pkt_e[20]),
    .C2(_0361_),
    .ZN(_0016_)
  );
  NOR3_X1 _0686_ (
    .A1(rx_pkt_s[20]),
    .A2(_0355_),
    .A3(_0356_),
    .ZN(_0017_)
  );
  AOI211_X1 _0687_ (
    .A(_0016_),
    .B(_0017_),
    .C1(_0288_),
    .C2(_0355_),
    .ZN(force_lit[6])
  );
  AOI221_X1 _0688_ (
    .A(_0002_),
    .B1(_0003_),
    .B2(rx_pkt_w[21]),
    .C1(rx_pkt_e[21]),
    .C2(_0361_),
    .ZN(_0018_)
  );
  NOR3_X1 _0689_ (
    .A1(rx_pkt_s[21]),
    .A2(_0355_),
    .A3(_0356_),
    .ZN(_0019_)
  );
  AOI211_X1 _0690_ (
    .A(_0018_),
    .B(_0019_),
    .C1(_0289_),
    .C2(_0355_),
    .ZN(force_lit[7])
  );
  AOI221_X1 _0691_ (
    .A(_0002_),
    .B1(_0003_),
    .B2(rx_pkt_w[22]),
    .C1(rx_pkt_e[22]),
    .C2(_0361_),
    .ZN(_0020_)
  );
  NOR3_X1 _0692_ (
    .A1(rx_pkt_s[22]),
    .A2(_0355_),
    .A3(_0356_),
    .ZN(_0021_)
  );
  AOI211_X1 _0693_ (
    .A(_0020_),
    .B(_0021_),
    .C1(_0290_),
    .C2(_0355_),
    .ZN(force_lit[8])
  );
  AOI221_X1 _0694_ (
    .A(_0002_),
    .B1(_0003_),
    .B2(rx_pkt_w[23]),
    .C1(rx_pkt_e[23]),
    .C2(_0361_),
    .ZN(_0022_)
  );
  NOR3_X1 _0695_ (
    .A1(rx_pkt_s[23]),
    .A2(_0355_),
    .A3(_0356_),
    .ZN(_0023_)
  );
  AOI211_X1 _0696_ (
    .A(_0022_),
    .B(_0023_),
    .C1(_0291_),
    .C2(_0355_),
    .ZN(force_lit[9])
  );
  AOI221_X1 _0697_ (
    .A(_0002_),
    .B1(_0003_),
    .B2(rx_pkt_w[24]),
    .C1(rx_pkt_e[24]),
    .C2(_0361_),
    .ZN(_0024_)
  );
  NOR3_X1 _0698_ (
    .A1(rx_pkt_s[24]),
    .A2(_0355_),
    .A3(_0356_),
    .ZN(_0025_)
  );
  AOI211_X1 _0699_ (
    .A(_0024_),
    .B(_0025_),
    .C1(_0292_),
    .C2(_0355_),
    .ZN(force_lit[10])
  );
  AOI221_X1 _0700_ (
    .A(_0002_),
    .B1(_0003_),
    .B2(rx_pkt_w[25]),
    .C1(rx_pkt_e[25]),
    .C2(_0361_),
    .ZN(_0026_)
  );
  NOR3_X1 _0701_ (
    .A1(rx_pkt_s[25]),
    .A2(_0355_),
    .A3(_0356_),
    .ZN(_0027_)
  );
  AOI211_X1 _0702_ (
    .A(_0026_),
    .B(_0027_),
    .C1(_0293_),
    .C2(_0355_),
    .ZN(force_lit[11])
  );
  AOI221_X1 _0703_ (
    .A(_0002_),
    .B1(_0003_),
    .B2(rx_pkt_w[26]),
    .C1(rx_pkt_e[26]),
    .C2(_0361_),
    .ZN(_0028_)
  );
  NOR3_X1 _0704_ (
    .A1(rx_pkt_s[26]),
    .A2(_0355_),
    .A3(_0356_),
    .ZN(_0029_)
  );
  AOI211_X1 _0705_ (
    .A(_0028_),
    .B(_0029_),
    .C1(_0294_),
    .C2(_0355_),
    .ZN(force_lit[12])
  );
  AOI221_X1 _0706_ (
    .A(_0002_),
    .B1(_0003_),
    .B2(rx_pkt_w[27]),
    .C1(rx_pkt_e[27]),
    .C2(_0361_),
    .ZN(_0030_)
  );
  NOR3_X1 _0707_ (
    .A1(rx_pkt_s[27]),
    .A2(_0355_),
    .A3(_0356_),
    .ZN(_0031_)
  );
  AOI211_X1 _0708_ (
    .A(_0030_),
    .B(_0031_),
    .C1(_0295_),
    .C2(_0355_),
    .ZN(force_lit[13])
  );
  AOI221_X1 _0709_ (
    .A(_0002_),
    .B1(_0003_),
    .B2(rx_pkt_w[28]),
    .C1(rx_pkt_e[28]),
    .C2(_0361_),
    .ZN(_0032_)
  );
  NOR3_X1 _0710_ (
    .A1(rx_pkt_s[28]),
    .A2(_0355_),
    .A3(_0356_),
    .ZN(_0033_)
  );
  AOI211_X1 _0711_ (
    .A(_0032_),
    .B(_0033_),
    .C1(_0296_),
    .C2(_0355_),
    .ZN(force_lit[14])
  );
  AOI221_X1 _0712_ (
    .A(_0002_),
    .B1(_0003_),
    .B2(rx_pkt_w[29]),
    .C1(rx_pkt_e[29]),
    .C2(_0361_),
    .ZN(_0034_)
  );
  NOR3_X1 _0713_ (
    .A1(rx_pkt_s[29]),
    .A2(_0355_),
    .A3(_0356_),
    .ZN(_0035_)
  );
  AOI211_X1 _0714_ (
    .A(_0034_),
    .B(_0035_),
    .C1(_0297_),
    .C2(_0355_),
    .ZN(force_lit[15])
  );
  AOI221_X1 _0715_ (
    .A(_0002_),
    .B1(_0003_),
    .B2(rx_pkt_w[30]),
    .C1(rx_pkt_e[30]),
    .C2(_0361_),
    .ZN(_0036_)
  );
  NOR3_X1 _0716_ (
    .A1(rx_pkt_s[30]),
    .A2(_0355_),
    .A3(_0356_),
    .ZN(_0037_)
  );
  AOI211_X1 _0717_ (
    .A(_0036_),
    .B(_0037_),
    .C1(_0298_),
    .C2(_0355_),
    .ZN(force_lit[16])
  );
  AOI221_X1 _0718_ (
    .A(_0002_),
    .B1(_0003_),
    .B2(rx_pkt_w[31]),
    .C1(rx_pkt_e[31]),
    .C2(_0361_),
    .ZN(_0038_)
  );
  NOR3_X1 _0719_ (
    .A1(rx_pkt_s[31]),
    .A2(_0355_),
    .A3(_0356_),
    .ZN(_0039_)
  );
  AOI211_X1 _0720_ (
    .A(_0038_),
    .B(_0039_),
    .C1(_0299_),
    .C2(_0355_),
    .ZN(force_lit[17])
  );
  AOI221_X1 _0721_ (
    .A(_0002_),
    .B1(_0003_),
    .B2(rx_pkt_w[32]),
    .C1(rx_pkt_e[32]),
    .C2(_0361_),
    .ZN(_0040_)
  );
  NOR3_X1 _0722_ (
    .A1(rx_pkt_s[32]),
    .A2(_0355_),
    .A3(_0356_),
    .ZN(_0041_)
  );
  AOI211_X1 _0723_ (
    .A(_0040_),
    .B(_0041_),
    .C1(_0300_),
    .C2(_0355_),
    .ZN(force_lit[18])
  );
  AOI221_X1 _0724_ (
    .A(_0002_),
    .B1(_0003_),
    .B2(rx_pkt_w[33]),
    .C1(rx_pkt_e[33]),
    .C2(_0361_),
    .ZN(_0042_)
  );
  NOR3_X1 _0725_ (
    .A1(rx_pkt_s[33]),
    .A2(_0355_),
    .A3(_0356_),
    .ZN(_0043_)
  );
  AOI211_X1 _0726_ (
    .A(_0042_),
    .B(_0043_),
    .C1(_0301_),
    .C2(_0355_),
    .ZN(force_lit[19])
  );
  AOI221_X1 _0727_ (
    .A(_0002_),
    .B1(_0003_),
    .B2(rx_pkt_w[34]),
    .C1(rx_pkt_e[34]),
    .C2(_0361_),
    .ZN(_0044_)
  );
  NOR3_X1 _0728_ (
    .A1(rx_pkt_s[34]),
    .A2(_0355_),
    .A3(_0356_),
    .ZN(_0045_)
  );
  AOI211_X1 _0729_ (
    .A(_0044_),
    .B(_0045_),
    .C1(_0302_),
    .C2(_0355_),
    .ZN(force_lit[20])
  );
  AOI221_X1 _0730_ (
    .A(_0002_),
    .B1(_0003_),
    .B2(rx_pkt_w[35]),
    .C1(rx_pkt_e[35]),
    .C2(_0361_),
    .ZN(_0046_)
  );
  NOR3_X1 _0731_ (
    .A1(rx_pkt_s[35]),
    .A2(_0355_),
    .A3(_0356_),
    .ZN(_0047_)
  );
  AOI211_X1 _0732_ (
    .A(_0046_),
    .B(_0047_),
    .C1(_0303_),
    .C2(_0355_),
    .ZN(force_lit[21])
  );
  AOI221_X1 _0733_ (
    .A(_0002_),
    .B1(_0003_),
    .B2(rx_pkt_w[36]),
    .C1(rx_pkt_e[36]),
    .C2(_0361_),
    .ZN(_0048_)
  );
  NOR3_X1 _0734_ (
    .A1(rx_pkt_s[36]),
    .A2(_0355_),
    .A3(_0356_),
    .ZN(_0049_)
  );
  AOI211_X1 _0735_ (
    .A(_0048_),
    .B(_0049_),
    .C1(_0304_),
    .C2(_0355_),
    .ZN(force_lit[22])
  );
  AOI221_X1 _0736_ (
    .A(_0002_),
    .B1(_0003_),
    .B2(rx_pkt_w[37]),
    .C1(rx_pkt_e[37]),
    .C2(_0361_),
    .ZN(_0050_)
  );
  NOR3_X1 _0737_ (
    .A1(rx_pkt_s[37]),
    .A2(_0355_),
    .A3(_0356_),
    .ZN(_0051_)
  );
  AOI211_X1 _0738_ (
    .A(_0050_),
    .B(_0051_),
    .C1(_0305_),
    .C2(_0355_),
    .ZN(force_lit[23])
  );
  AOI221_X1 _0739_ (
    .A(_0002_),
    .B1(_0003_),
    .B2(rx_pkt_w[38]),
    .C1(rx_pkt_e[38]),
    .C2(_0361_),
    .ZN(_0052_)
  );
  NOR3_X1 _0740_ (
    .A1(rx_pkt_s[38]),
    .A2(_0355_),
    .A3(_0356_),
    .ZN(_0053_)
  );
  AOI211_X1 _0741_ (
    .A(_0052_),
    .B(_0053_),
    .C1(_0306_),
    .C2(_0355_),
    .ZN(force_lit[24])
  );
  AOI221_X1 _0742_ (
    .A(_0002_),
    .B1(_0003_),
    .B2(rx_pkt_w[39]),
    .C1(rx_pkt_e[39]),
    .C2(_0361_),
    .ZN(_0054_)
  );
  NOR3_X1 _0743_ (
    .A1(rx_pkt_s[39]),
    .A2(_0355_),
    .A3(_0356_),
    .ZN(_0055_)
  );
  AOI211_X1 _0744_ (
    .A(_0054_),
    .B(_0055_),
    .C1(_0307_),
    .C2(_0355_),
    .ZN(force_lit[25])
  );
  AOI221_X1 _0745_ (
    .A(_0002_),
    .B1(_0003_),
    .B2(rx_pkt_w[40]),
    .C1(rx_pkt_e[40]),
    .C2(_0361_),
    .ZN(_0056_)
  );
  NOR3_X1 _0746_ (
    .A1(rx_pkt_s[40]),
    .A2(_0355_),
    .A3(_0356_),
    .ZN(_0057_)
  );
  AOI211_X1 _0747_ (
    .A(_0056_),
    .B(_0057_),
    .C1(_0308_),
    .C2(_0355_),
    .ZN(force_lit[26])
  );
  AOI221_X1 _0748_ (
    .A(_0002_),
    .B1(_0003_),
    .B2(rx_pkt_w[41]),
    .C1(rx_pkt_e[41]),
    .C2(_0361_),
    .ZN(_0058_)
  );
  NOR3_X1 _0749_ (
    .A1(rx_pkt_s[41]),
    .A2(_0355_),
    .A3(_0356_),
    .ZN(_0059_)
  );
  AOI211_X1 _0750_ (
    .A(_0058_),
    .B(_0059_),
    .C1(_0309_),
    .C2(_0355_),
    .ZN(force_lit[27])
  );
  AOI221_X1 _0751_ (
    .A(_0002_),
    .B1(_0003_),
    .B2(rx_pkt_w[42]),
    .C1(rx_pkt_e[42]),
    .C2(_0361_),
    .ZN(_0060_)
  );
  NOR3_X1 _0752_ (
    .A1(rx_pkt_s[42]),
    .A2(_0355_),
    .A3(_0356_),
    .ZN(_0061_)
  );
  AOI211_X1 _0753_ (
    .A(_0060_),
    .B(_0061_),
    .C1(_0310_),
    .C2(_0355_),
    .ZN(force_lit[28])
  );
  AOI221_X1 _0754_ (
    .A(_0002_),
    .B1(_0003_),
    .B2(rx_pkt_w[43]),
    .C1(rx_pkt_e[43]),
    .C2(_0361_),
    .ZN(_0062_)
  );
  NOR3_X1 _0755_ (
    .A1(rx_pkt_s[43]),
    .A2(_0355_),
    .A3(_0356_),
    .ZN(_0063_)
  );
  AOI211_X1 _0756_ (
    .A(_0062_),
    .B(_0063_),
    .C1(_0311_),
    .C2(_0355_),
    .ZN(force_lit[29])
  );
  AOI221_X1 _0757_ (
    .A(_0002_),
    .B1(_0003_),
    .B2(rx_pkt_w[44]),
    .C1(rx_pkt_e[44]),
    .C2(_0361_),
    .ZN(_0064_)
  );
  NOR3_X1 _0758_ (
    .A1(rx_pkt_s[44]),
    .A2(_0355_),
    .A3(_0356_),
    .ZN(_0065_)
  );
  AOI211_X1 _0759_ (
    .A(_0064_),
    .B(_0065_),
    .C1(_0312_),
    .C2(_0355_),
    .ZN(force_lit[30])
  );
  NOR3_X1 _0760_ (
    .A1(rx_pkt_s[45]),
    .A2(_0355_),
    .A3(_0356_),
    .ZN(_0066_)
  );
  AOI221_X1 _0761_ (
    .A(_0002_),
    .B1(_0003_),
    .B2(rx_pkt_w[45]),
    .C1(rx_pkt_e[45]),
    .C2(_0361_),
    .ZN(_0067_)
  );
  AOI211_X1 _0762_ (
    .A(_0066_),
    .B(_0067_),
    .C1(_0313_),
    .C2(_0355_),
    .ZN(force_lit[31])
  );
  NOR3_X1 _0763_ (
    .A1(_0360_),
    .A2(_0361_),
    .A3(_0002_),
    .ZN(_0068_)
  );
  INV_X1 _0764_ (
    .A(_0068_),
    .ZN(force_valid)
  );
  AND3_X1 _0765_ (
    .A1(rx_pkt_s[78]),
    .A2(_0239_),
    .A3(rx_valid_s),
    .ZN(_0069_)
  );
  NAND3_X1 _0766_ (
    .A1(rx_pkt_s[78]),
    .A2(_0239_),
    .A3(rx_valid_s),
    .ZN(_0070_)
  );
  NAND3_X1 _0767_ (
    .A1(rx_pkt_e[78]),
    .A2(_0240_),
    .A3(rx_valid_e),
    .ZN(_0071_)
  );
  AND4_X1 _0768_ (
    .A1(rx_pkt_w[78]),
    .A2(_0358_),
    .A3(_0070_),
    .A4(_0071_),
    .ZN(_0072_)
  );
  NAND2_X1 _0769_ (
    .A1(rx_pkt_w[14]),
    .A2(_0072_),
    .ZN(_0073_)
  );
  NOR2_X1 _0770_ (
    .A1(_0069_),
    .A2(_0071_),
    .ZN(_0074_)
  );
  AND3_X1 _0771_ (
    .A1(rx_pkt_n[78]),
    .A2(_0238_),
    .A3(rx_valid_n),
    .ZN(_0075_)
  );
  NAND3_X1 _0772_ (
    .A1(rx_pkt_n[78]),
    .A2(_0238_),
    .A3(rx_valid_n),
    .ZN(_0076_)
  );
  AOI221_X1 _0773_ (
    .A(_0075_),
    .B1(_0069_),
    .B2(rx_pkt_s[14]),
    .C1(rx_pkt_e[14]),
    .C2(_0074_),
    .ZN(_0077_)
  );
  AOI221_X1 _0774_ (
    .A(force_valid),
    .B1(_0073_),
    .B2(_0077_),
    .C1(_0075_),
    .C2(_0282_),
    .ZN(clause_rx_ptr[0])
  );
  NAND2_X1 _0775_ (
    .A1(rx_pkt_w[15]),
    .A2(_0072_),
    .ZN(_0078_)
  );
  AOI221_X1 _0776_ (
    .A(_0075_),
    .B1(_0069_),
    .B2(rx_pkt_s[15]),
    .C1(rx_pkt_e[15]),
    .C2(_0074_),
    .ZN(_0079_)
  );
  AOI221_X1 _0777_ (
    .A(force_valid),
    .B1(_0078_),
    .B2(_0079_),
    .C1(_0075_),
    .C2(_0283_),
    .ZN(clause_rx_ptr[1])
  );
  NAND2_X1 _0778_ (
    .A1(rx_pkt_w[16]),
    .A2(_0072_),
    .ZN(_0080_)
  );
  AOI221_X1 _0779_ (
    .A(_0075_),
    .B1(_0069_),
    .B2(rx_pkt_s[16]),
    .C1(rx_pkt_e[16]),
    .C2(_0074_),
    .ZN(_0081_)
  );
  AOI221_X1 _0780_ (
    .A(force_valid),
    .B1(_0080_),
    .B2(_0081_),
    .C1(_0075_),
    .C2(_0284_),
    .ZN(clause_rx_ptr[2])
  );
  NAND2_X1 _0781_ (
    .A1(rx_pkt_w[17]),
    .A2(_0072_),
    .ZN(_0082_)
  );
  AOI221_X1 _0782_ (
    .A(_0075_),
    .B1(_0069_),
    .B2(rx_pkt_s[17]),
    .C1(rx_pkt_e[17]),
    .C2(_0074_),
    .ZN(_0083_)
  );
  AOI221_X1 _0783_ (
    .A(force_valid),
    .B1(_0082_),
    .B2(_0083_),
    .C1(_0075_),
    .C2(_0285_),
    .ZN(clause_rx_ptr[3])
  );
  NAND2_X1 _0784_ (
    .A1(rx_pkt_w[18]),
    .A2(_0072_),
    .ZN(_0084_)
  );
  AOI221_X1 _0785_ (
    .A(_0075_),
    .B1(_0069_),
    .B2(rx_pkt_s[18]),
    .C1(rx_pkt_e[18]),
    .C2(_0074_),
    .ZN(_0085_)
  );
  AOI221_X1 _0786_ (
    .A(force_valid),
    .B1(_0084_),
    .B2(_0085_),
    .C1(_0075_),
    .C2(_0286_),
    .ZN(clause_rx_ptr[4])
  );
  NAND2_X1 _0787_ (
    .A1(rx_pkt_w[19]),
    .A2(_0072_),
    .ZN(_0086_)
  );
  AOI221_X1 _0788_ (
    .A(_0075_),
    .B1(_0069_),
    .B2(rx_pkt_s[19]),
    .C1(rx_pkt_e[19]),
    .C2(_0074_),
    .ZN(_0087_)
  );
  AOI221_X1 _0789_ (
    .A(force_valid),
    .B1(_0086_),
    .B2(_0087_),
    .C1(_0075_),
    .C2(_0287_),
    .ZN(clause_rx_ptr[5])
  );
  NAND2_X1 _0790_ (
    .A1(rx_pkt_w[20]),
    .A2(_0072_),
    .ZN(_0088_)
  );
  AOI221_X1 _0791_ (
    .A(_0075_),
    .B1(_0069_),
    .B2(rx_pkt_s[20]),
    .C1(rx_pkt_e[20]),
    .C2(_0074_),
    .ZN(_0089_)
  );
  AOI221_X1 _0792_ (
    .A(force_valid),
    .B1(_0088_),
    .B2(_0089_),
    .C1(_0075_),
    .C2(_0288_),
    .ZN(clause_rx_ptr[6])
  );
  NAND2_X1 _0793_ (
    .A1(rx_pkt_w[21]),
    .A2(_0072_),
    .ZN(_0090_)
  );
  AOI221_X1 _0794_ (
    .A(_0075_),
    .B1(_0069_),
    .B2(rx_pkt_s[21]),
    .C1(rx_pkt_e[21]),
    .C2(_0074_),
    .ZN(_0091_)
  );
  AOI221_X1 _0795_ (
    .A(force_valid),
    .B1(_0090_),
    .B2(_0091_),
    .C1(_0075_),
    .C2(_0289_),
    .ZN(clause_rx_ptr[7])
  );
  NAND2_X1 _0796_ (
    .A1(rx_pkt_w[22]),
    .A2(_0072_),
    .ZN(_0092_)
  );
  AOI221_X1 _0797_ (
    .A(_0075_),
    .B1(_0069_),
    .B2(rx_pkt_s[22]),
    .C1(rx_pkt_e[22]),
    .C2(_0074_),
    .ZN(_0093_)
  );
  AOI221_X1 _0798_ (
    .A(force_valid),
    .B1(_0092_),
    .B2(_0093_),
    .C1(_0075_),
    .C2(_0290_),
    .ZN(clause_rx_ptr[8])
  );
  NAND2_X1 _0799_ (
    .A1(rx_pkt_w[23]),
    .A2(_0072_),
    .ZN(_0094_)
  );
  AOI221_X1 _0800_ (
    .A(_0075_),
    .B1(_0069_),
    .B2(rx_pkt_s[23]),
    .C1(rx_pkt_e[23]),
    .C2(_0074_),
    .ZN(_0095_)
  );
  AOI221_X1 _0801_ (
    .A(force_valid),
    .B1(_0094_),
    .B2(_0095_),
    .C1(_0075_),
    .C2(_0291_),
    .ZN(clause_rx_ptr[9])
  );
  NAND2_X1 _0802_ (
    .A1(rx_pkt_w[24]),
    .A2(_0072_),
    .ZN(_0096_)
  );
  AOI221_X1 _0803_ (
    .A(_0075_),
    .B1(_0069_),
    .B2(rx_pkt_s[24]),
    .C1(rx_pkt_e[24]),
    .C2(_0074_),
    .ZN(_0097_)
  );
  AOI221_X1 _0804_ (
    .A(force_valid),
    .B1(_0096_),
    .B2(_0097_),
    .C1(_0075_),
    .C2(_0292_),
    .ZN(clause_rx_ptr[10])
  );
  NAND2_X1 _0805_ (
    .A1(rx_pkt_w[25]),
    .A2(_0072_),
    .ZN(_0098_)
  );
  AOI221_X1 _0806_ (
    .A(_0075_),
    .B1(_0069_),
    .B2(rx_pkt_s[25]),
    .C1(rx_pkt_e[25]),
    .C2(_0074_),
    .ZN(_0099_)
  );
  AOI221_X1 _0807_ (
    .A(force_valid),
    .B1(_0098_),
    .B2(_0099_),
    .C1(_0075_),
    .C2(_0293_),
    .ZN(clause_rx_ptr[11])
  );
  NAND2_X1 _0808_ (
    .A1(rx_pkt_w[26]),
    .A2(_0072_),
    .ZN(_0100_)
  );
  AOI221_X1 _0809_ (
    .A(_0075_),
    .B1(_0069_),
    .B2(rx_pkt_s[26]),
    .C1(rx_pkt_e[26]),
    .C2(_0074_),
    .ZN(_0101_)
  );
  AOI221_X1 _0810_ (
    .A(force_valid),
    .B1(_0100_),
    .B2(_0101_),
    .C1(_0075_),
    .C2(_0294_),
    .ZN(clause_rx_ptr[12])
  );
  NAND2_X1 _0811_ (
    .A1(rx_pkt_w[27]),
    .A2(_0072_),
    .ZN(_0102_)
  );
  AOI221_X1 _0812_ (
    .A(_0075_),
    .B1(_0069_),
    .B2(rx_pkt_s[27]),
    .C1(rx_pkt_e[27]),
    .C2(_0074_),
    .ZN(_0103_)
  );
  AOI221_X1 _0813_ (
    .A(force_valid),
    .B1(_0102_),
    .B2(_0103_),
    .C1(_0075_),
    .C2(_0295_),
    .ZN(clause_rx_ptr[13])
  );
  NAND2_X1 _0814_ (
    .A1(rx_pkt_w[28]),
    .A2(_0072_),
    .ZN(_0104_)
  );
  AOI221_X1 _0815_ (
    .A(_0075_),
    .B1(_0069_),
    .B2(rx_pkt_s[28]),
    .C1(rx_pkt_e[28]),
    .C2(_0074_),
    .ZN(_0105_)
  );
  AOI221_X1 _0816_ (
    .A(force_valid),
    .B1(_0104_),
    .B2(_0105_),
    .C1(_0075_),
    .C2(_0296_),
    .ZN(clause_rx_ptr[14])
  );
  NAND2_X1 _0817_ (
    .A1(rx_pkt_w[29]),
    .A2(_0072_),
    .ZN(_0106_)
  );
  AOI221_X1 _0818_ (
    .A(_0075_),
    .B1(_0069_),
    .B2(rx_pkt_s[29]),
    .C1(rx_pkt_e[29]),
    .C2(_0074_),
    .ZN(_0107_)
  );
  AOI221_X1 _0819_ (
    .A(force_valid),
    .B1(_0106_),
    .B2(_0107_),
    .C1(_0075_),
    .C2(_0297_),
    .ZN(clause_rx_ptr[15])
  );
  NAND2_X1 _0820_ (
    .A1(rx_pkt_w[30]),
    .A2(_0072_),
    .ZN(_0108_)
  );
  AOI221_X1 _0821_ (
    .A(_0075_),
    .B1(_0069_),
    .B2(rx_pkt_s[30]),
    .C1(rx_pkt_e[30]),
    .C2(_0074_),
    .ZN(_0109_)
  );
  AOI221_X1 _0822_ (
    .A(force_valid),
    .B1(_0108_),
    .B2(_0109_),
    .C1(_0075_),
    .C2(_0298_),
    .ZN(clause_rx_ptr[16])
  );
  NAND2_X1 _0823_ (
    .A1(rx_pkt_w[31]),
    .A2(_0072_),
    .ZN(_0110_)
  );
  AOI221_X1 _0824_ (
    .A(_0075_),
    .B1(_0069_),
    .B2(rx_pkt_s[31]),
    .C1(rx_pkt_e[31]),
    .C2(_0074_),
    .ZN(_0111_)
  );
  AOI221_X1 _0825_ (
    .A(force_valid),
    .B1(_0110_),
    .B2(_0111_),
    .C1(_0075_),
    .C2(_0299_),
    .ZN(clause_rx_ptr[17])
  );
  NAND2_X1 _0826_ (
    .A1(rx_pkt_w[32]),
    .A2(_0072_),
    .ZN(_0112_)
  );
  AOI221_X1 _0827_ (
    .A(_0075_),
    .B1(_0069_),
    .B2(rx_pkt_s[32]),
    .C1(rx_pkt_e[32]),
    .C2(_0074_),
    .ZN(_0113_)
  );
  AOI221_X1 _0828_ (
    .A(force_valid),
    .B1(_0112_),
    .B2(_0113_),
    .C1(_0075_),
    .C2(_0300_),
    .ZN(clause_rx_ptr[18])
  );
  NAND2_X1 _0829_ (
    .A1(rx_pkt_w[33]),
    .A2(_0072_),
    .ZN(_0114_)
  );
  AOI221_X1 _0830_ (
    .A(_0075_),
    .B1(_0069_),
    .B2(rx_pkt_s[33]),
    .C1(rx_pkt_e[33]),
    .C2(_0074_),
    .ZN(_0115_)
  );
  AOI221_X1 _0831_ (
    .A(force_valid),
    .B1(_0114_),
    .B2(_0115_),
    .C1(_0075_),
    .C2(_0301_),
    .ZN(clause_rx_ptr[19])
  );
  NAND2_X1 _0832_ (
    .A1(rx_pkt_w[34]),
    .A2(_0072_),
    .ZN(_0116_)
  );
  AOI221_X1 _0833_ (
    .A(_0075_),
    .B1(_0069_),
    .B2(rx_pkt_s[34]),
    .C1(rx_pkt_e[34]),
    .C2(_0074_),
    .ZN(_0117_)
  );
  AOI221_X1 _0834_ (
    .A(force_valid),
    .B1(_0116_),
    .B2(_0117_),
    .C1(_0075_),
    .C2(_0302_),
    .ZN(clause_rx_ptr[20])
  );
  NAND2_X1 _0835_ (
    .A1(rx_pkt_w[35]),
    .A2(_0072_),
    .ZN(_0118_)
  );
  AOI221_X1 _0836_ (
    .A(_0075_),
    .B1(_0069_),
    .B2(rx_pkt_s[35]),
    .C1(rx_pkt_e[35]),
    .C2(_0074_),
    .ZN(_0119_)
  );
  AOI221_X1 _0837_ (
    .A(force_valid),
    .B1(_0118_),
    .B2(_0119_),
    .C1(_0075_),
    .C2(_0303_),
    .ZN(clause_rx_ptr[21])
  );
  NAND2_X1 _0838_ (
    .A1(rx_pkt_w[36]),
    .A2(_0072_),
    .ZN(_0120_)
  );
  AOI221_X1 _0839_ (
    .A(_0075_),
    .B1(_0069_),
    .B2(rx_pkt_s[36]),
    .C1(rx_pkt_e[36]),
    .C2(_0074_),
    .ZN(_0121_)
  );
  AOI221_X1 _0840_ (
    .A(force_valid),
    .B1(_0120_),
    .B2(_0121_),
    .C1(_0075_),
    .C2(_0304_),
    .ZN(clause_rx_ptr[22])
  );
  NAND2_X1 _0841_ (
    .A1(rx_pkt_w[37]),
    .A2(_0072_),
    .ZN(_0122_)
  );
  AOI221_X1 _0842_ (
    .A(_0075_),
    .B1(_0069_),
    .B2(rx_pkt_s[37]),
    .C1(rx_pkt_e[37]),
    .C2(_0074_),
    .ZN(_0123_)
  );
  AOI221_X1 _0843_ (
    .A(force_valid),
    .B1(_0122_),
    .B2(_0123_),
    .C1(_0075_),
    .C2(_0305_),
    .ZN(clause_rx_ptr[23])
  );
  NAND2_X1 _0844_ (
    .A1(rx_pkt_w[38]),
    .A2(_0072_),
    .ZN(_0124_)
  );
  AOI221_X1 _0845_ (
    .A(_0075_),
    .B1(_0069_),
    .B2(rx_pkt_s[38]),
    .C1(rx_pkt_e[38]),
    .C2(_0074_),
    .ZN(_0125_)
  );
  AOI221_X1 _0846_ (
    .A(force_valid),
    .B1(_0124_),
    .B2(_0125_),
    .C1(_0075_),
    .C2(_0306_),
    .ZN(clause_rx_ptr[24])
  );
  NAND2_X1 _0847_ (
    .A1(rx_pkt_w[39]),
    .A2(_0072_),
    .ZN(_0126_)
  );
  AOI221_X1 _0848_ (
    .A(_0075_),
    .B1(_0069_),
    .B2(rx_pkt_s[39]),
    .C1(rx_pkt_e[39]),
    .C2(_0074_),
    .ZN(_0127_)
  );
  AOI221_X1 _0849_ (
    .A(force_valid),
    .B1(_0126_),
    .B2(_0127_),
    .C1(_0075_),
    .C2(_0307_),
    .ZN(clause_rx_ptr[25])
  );
  NAND2_X1 _0850_ (
    .A1(rx_pkt_w[40]),
    .A2(_0072_),
    .ZN(_0128_)
  );
  AOI221_X1 _0851_ (
    .A(_0075_),
    .B1(_0069_),
    .B2(rx_pkt_s[40]),
    .C1(rx_pkt_e[40]),
    .C2(_0074_),
    .ZN(_0129_)
  );
  AOI221_X1 _0852_ (
    .A(force_valid),
    .B1(_0128_),
    .B2(_0129_),
    .C1(_0075_),
    .C2(_0308_),
    .ZN(clause_rx_ptr[26])
  );
  NAND2_X1 _0853_ (
    .A1(rx_pkt_w[41]),
    .A2(_0072_),
    .ZN(_0130_)
  );
  AOI221_X1 _0854_ (
    .A(_0075_),
    .B1(_0069_),
    .B2(rx_pkt_s[41]),
    .C1(rx_pkt_e[41]),
    .C2(_0074_),
    .ZN(_0131_)
  );
  AOI221_X1 _0855_ (
    .A(force_valid),
    .B1(_0130_),
    .B2(_0131_),
    .C1(_0075_),
    .C2(_0309_),
    .ZN(clause_rx_ptr[27])
  );
  NAND2_X1 _0856_ (
    .A1(rx_pkt_w[42]),
    .A2(_0072_),
    .ZN(_0132_)
  );
  AOI221_X1 _0857_ (
    .A(_0075_),
    .B1(_0069_),
    .B2(rx_pkt_s[42]),
    .C1(rx_pkt_e[42]),
    .C2(_0074_),
    .ZN(_0133_)
  );
  AOI221_X1 _0858_ (
    .A(force_valid),
    .B1(_0132_),
    .B2(_0133_),
    .C1(_0075_),
    .C2(_0310_),
    .ZN(clause_rx_ptr[28])
  );
  NAND2_X1 _0859_ (
    .A1(rx_pkt_w[43]),
    .A2(_0072_),
    .ZN(_0134_)
  );
  AOI221_X1 _0860_ (
    .A(_0075_),
    .B1(_0069_),
    .B2(rx_pkt_s[43]),
    .C1(rx_pkt_e[43]),
    .C2(_0074_),
    .ZN(_0135_)
  );
  AOI221_X1 _0861_ (
    .A(force_valid),
    .B1(_0134_),
    .B2(_0135_),
    .C1(_0075_),
    .C2(_0311_),
    .ZN(clause_rx_ptr[29])
  );
  NAND2_X1 _0862_ (
    .A1(rx_pkt_w[44]),
    .A2(_0072_),
    .ZN(_0136_)
  );
  AOI221_X1 _0863_ (
    .A(_0075_),
    .B1(_0069_),
    .B2(rx_pkt_s[44]),
    .C1(rx_pkt_e[44]),
    .C2(_0074_),
    .ZN(_0137_)
  );
  AOI221_X1 _0864_ (
    .A(force_valid),
    .B1(_0136_),
    .B2(_0137_),
    .C1(_0075_),
    .C2(_0312_),
    .ZN(clause_rx_ptr[30])
  );
  NAND2_X1 _0865_ (
    .A1(rx_pkt_w[45]),
    .A2(_0072_),
    .ZN(_0138_)
  );
  AOI221_X1 _0866_ (
    .A(_0075_),
    .B1(_0069_),
    .B2(rx_pkt_s[45]),
    .C1(rx_pkt_e[45]),
    .C2(_0074_),
    .ZN(_0139_)
  );
  AOI221_X1 _0867_ (
    .A(force_valid),
    .B1(_0138_),
    .B2(_0139_),
    .C1(_0075_),
    .C2(_0313_),
    .ZN(clause_rx_ptr[31])
  );
  AOI222_X1 _0868_ (
    .A1(rx_pkt_w[46]),
    .A2(_0072_),
    .B1(_0074_),
    .B2(rx_pkt_e[46]),
    .C1(rx_pkt_s[46]),
    .C2(_0069_),
    .ZN(_0140_)
  );
  OAI21_X1 _0869_ (
    .A(_0068_),
    .B1(_0076_),
    .B2(rx_pkt_n[46]),
    .ZN(_0141_)
  );
  AOI21_X1 _0870_ (
    .A(_0141_),
    .B1(_0140_),
    .B2(_0076_),
    .ZN(clause_rx_ptr[32])
  );
  AOI222_X1 _0871_ (
    .A1(rx_pkt_w[47]),
    .A2(_0072_),
    .B1(_0074_),
    .B2(rx_pkt_e[47]),
    .C1(rx_pkt_s[47]),
    .C2(_0069_),
    .ZN(_0142_)
  );
  OAI21_X1 _0872_ (
    .A(_0068_),
    .B1(_0076_),
    .B2(rx_pkt_n[47]),
    .ZN(_0143_)
  );
  AOI21_X1 _0873_ (
    .A(_0143_),
    .B1(_0142_),
    .B2(_0076_),
    .ZN(clause_rx_ptr[33])
  );
  AOI222_X1 _0874_ (
    .A1(rx_pkt_w[48]),
    .A2(_0072_),
    .B1(_0074_),
    .B2(rx_pkt_e[48]),
    .C1(rx_pkt_s[48]),
    .C2(_0069_),
    .ZN(_0144_)
  );
  OAI21_X1 _0875_ (
    .A(_0068_),
    .B1(_0076_),
    .B2(rx_pkt_n[48]),
    .ZN(_0145_)
  );
  AOI21_X1 _0876_ (
    .A(_0145_),
    .B1(_0144_),
    .B2(_0076_),
    .ZN(clause_rx_ptr[34])
  );
  AOI222_X1 _0877_ (
    .A1(rx_pkt_w[49]),
    .A2(_0072_),
    .B1(_0074_),
    .B2(rx_pkt_e[49]),
    .C1(rx_pkt_s[49]),
    .C2(_0069_),
    .ZN(_0146_)
  );
  OAI21_X1 _0878_ (
    .A(_0068_),
    .B1(_0076_),
    .B2(rx_pkt_n[49]),
    .ZN(_0147_)
  );
  AOI21_X1 _0879_ (
    .A(_0147_),
    .B1(_0146_),
    .B2(_0076_),
    .ZN(clause_rx_ptr[35])
  );
  AOI222_X1 _0880_ (
    .A1(rx_pkt_w[50]),
    .A2(_0072_),
    .B1(_0074_),
    .B2(rx_pkt_e[50]),
    .C1(rx_pkt_s[50]),
    .C2(_0069_),
    .ZN(_0148_)
  );
  OAI21_X1 _0881_ (
    .A(_0068_),
    .B1(_0076_),
    .B2(rx_pkt_n[50]),
    .ZN(_0149_)
  );
  AOI21_X1 _0882_ (
    .A(_0149_),
    .B1(_0148_),
    .B2(_0076_),
    .ZN(clause_rx_ptr[36])
  );
  AOI222_X1 _0883_ (
    .A1(rx_pkt_w[51]),
    .A2(_0072_),
    .B1(_0074_),
    .B2(rx_pkt_e[51]),
    .C1(rx_pkt_s[51]),
    .C2(_0069_),
    .ZN(_0150_)
  );
  OAI21_X1 _0884_ (
    .A(_0068_),
    .B1(_0076_),
    .B2(rx_pkt_n[51]),
    .ZN(_0151_)
  );
  AOI21_X1 _0885_ (
    .A(_0151_),
    .B1(_0150_),
    .B2(_0076_),
    .ZN(clause_rx_ptr[37])
  );
  AOI222_X1 _0886_ (
    .A1(rx_pkt_w[52]),
    .A2(_0072_),
    .B1(_0074_),
    .B2(rx_pkt_e[52]),
    .C1(rx_pkt_s[52]),
    .C2(_0069_),
    .ZN(_0152_)
  );
  OAI21_X1 _0887_ (
    .A(_0068_),
    .B1(_0076_),
    .B2(rx_pkt_n[52]),
    .ZN(_0153_)
  );
  AOI21_X1 _0888_ (
    .A(_0153_),
    .B1(_0152_),
    .B2(_0076_),
    .ZN(clause_rx_ptr[38])
  );
  NAND2_X1 _0889_ (
    .A1(rx_pkt_w[53]),
    .A2(_0072_),
    .ZN(_0154_)
  );
  AOI221_X1 _0890_ (
    .A(_0075_),
    .B1(_0069_),
    .B2(rx_pkt_s[53]),
    .C1(rx_pkt_e[53]),
    .C2(_0074_),
    .ZN(_0155_)
  );
  OAI21_X1 _0891_ (
    .A(_0068_),
    .B1(_0076_),
    .B2(rx_pkt_n[53]),
    .ZN(_0156_)
  );
  AOI21_X1 _0892_ (
    .A(_0156_),
    .B1(_0155_),
    .B2(_0154_),
    .ZN(clause_rx_ptr[39])
  );
  NAND2_X1 _0893_ (
    .A1(rx_pkt_w[54]),
    .A2(_0072_),
    .ZN(_0157_)
  );
  AOI221_X1 _0894_ (
    .A(_0075_),
    .B1(_0069_),
    .B2(rx_pkt_s[54]),
    .C1(rx_pkt_e[54]),
    .C2(_0074_),
    .ZN(_0158_)
  );
  OAI21_X1 _0895_ (
    .A(_0068_),
    .B1(_0076_),
    .B2(rx_pkt_n[54]),
    .ZN(_0159_)
  );
  AOI21_X1 _0896_ (
    .A(_0159_),
    .B1(_0158_),
    .B2(_0157_),
    .ZN(clause_rx_ptr[40])
  );
  AOI222_X1 _0897_ (
    .A1(rx_pkt_w[55]),
    .A2(_0072_),
    .B1(_0074_),
    .B2(rx_pkt_e[55]),
    .C1(rx_pkt_s[55]),
    .C2(_0069_),
    .ZN(_0160_)
  );
  OAI21_X1 _0898_ (
    .A(_0068_),
    .B1(_0076_),
    .B2(rx_pkt_n[55]),
    .ZN(_0161_)
  );
  AOI21_X1 _0899_ (
    .A(_0161_),
    .B1(_0160_),
    .B2(_0076_),
    .ZN(clause_rx_ptr[41])
  );
  AOI222_X1 _0900_ (
    .A1(rx_pkt_w[56]),
    .A2(_0072_),
    .B1(_0074_),
    .B2(rx_pkt_e[56]),
    .C1(rx_pkt_s[56]),
    .C2(_0069_),
    .ZN(_0162_)
  );
  OAI21_X1 _0901_ (
    .A(_0068_),
    .B1(_0076_),
    .B2(rx_pkt_n[56]),
    .ZN(_0163_)
  );
  AOI21_X1 _0902_ (
    .A(_0163_),
    .B1(_0162_),
    .B2(_0076_),
    .ZN(clause_rx_ptr[42])
  );
  AOI222_X1 _0903_ (
    .A1(rx_pkt_w[57]),
    .A2(_0072_),
    .B1(_0074_),
    .B2(rx_pkt_e[57]),
    .C1(rx_pkt_s[57]),
    .C2(_0069_),
    .ZN(_0164_)
  );
  OAI21_X1 _0904_ (
    .A(_0068_),
    .B1(_0076_),
    .B2(rx_pkt_n[57]),
    .ZN(_0165_)
  );
  AOI21_X1 _0905_ (
    .A(_0165_),
    .B1(_0164_),
    .B2(_0076_),
    .ZN(clause_rx_ptr[43])
  );
  AOI222_X1 _0906_ (
    .A1(rx_pkt_w[58]),
    .A2(_0072_),
    .B1(_0074_),
    .B2(rx_pkt_e[58]),
    .C1(rx_pkt_s[58]),
    .C2(_0069_),
    .ZN(_0166_)
  );
  OAI21_X1 _0907_ (
    .A(_0068_),
    .B1(_0076_),
    .B2(rx_pkt_n[58]),
    .ZN(_0167_)
  );
  AOI21_X1 _0908_ (
    .A(_0167_),
    .B1(_0166_),
    .B2(_0076_),
    .ZN(clause_rx_ptr[44])
  );
  AOI222_X1 _0909_ (
    .A1(rx_pkt_w[59]),
    .A2(_0072_),
    .B1(_0074_),
    .B2(rx_pkt_e[59]),
    .C1(rx_pkt_s[59]),
    .C2(_0069_),
    .ZN(_0168_)
  );
  OAI21_X1 _0910_ (
    .A(_0068_),
    .B1(_0076_),
    .B2(rx_pkt_n[59]),
    .ZN(_0169_)
  );
  AOI21_X1 _0911_ (
    .A(_0169_),
    .B1(_0168_),
    .B2(_0076_),
    .ZN(clause_rx_ptr[45])
  );
  AOI222_X1 _0912_ (
    .A1(rx_pkt_w[60]),
    .A2(_0072_),
    .B1(_0074_),
    .B2(rx_pkt_e[60]),
    .C1(rx_pkt_s[60]),
    .C2(_0069_),
    .ZN(_0170_)
  );
  OAI21_X1 _0913_ (
    .A(_0068_),
    .B1(_0076_),
    .B2(rx_pkt_n[60]),
    .ZN(_0171_)
  );
  AOI21_X1 _0914_ (
    .A(_0171_),
    .B1(_0170_),
    .B2(_0076_),
    .ZN(clause_rx_ptr[46])
  );
  NAND2_X1 _0915_ (
    .A1(rx_pkt_w[61]),
    .A2(_0072_),
    .ZN(_0172_)
  );
  AOI221_X1 _0916_ (
    .A(_0075_),
    .B1(_0069_),
    .B2(rx_pkt_s[61]),
    .C1(rx_pkt_e[61]),
    .C2(_0074_),
    .ZN(_0173_)
  );
  OAI21_X1 _0917_ (
    .A(_0068_),
    .B1(_0076_),
    .B2(rx_pkt_n[61]),
    .ZN(_0174_)
  );
  AOI21_X1 _0918_ (
    .A(_0174_),
    .B1(_0173_),
    .B2(_0172_),
    .ZN(clause_rx_ptr[47])
  );
  NAND2_X1 _0919_ (
    .A1(rx_pkt_w[62]),
    .A2(_0072_),
    .ZN(_0175_)
  );
  AOI221_X1 _0920_ (
    .A(_0075_),
    .B1(_0069_),
    .B2(rx_pkt_s[62]),
    .C1(rx_pkt_e[62]),
    .C2(_0074_),
    .ZN(_0176_)
  );
  OAI21_X1 _0921_ (
    .A(_0068_),
    .B1(_0076_),
    .B2(rx_pkt_n[62]),
    .ZN(_0177_)
  );
  AOI21_X1 _0922_ (
    .A(_0177_),
    .B1(_0176_),
    .B2(_0175_),
    .ZN(clause_rx_ptr[48])
  );
  NAND2_X1 _0923_ (
    .A1(rx_pkt_w[63]),
    .A2(_0072_),
    .ZN(_0178_)
  );
  AOI221_X1 _0924_ (
    .A(_0075_),
    .B1(_0069_),
    .B2(rx_pkt_s[63]),
    .C1(rx_pkt_e[63]),
    .C2(_0074_),
    .ZN(_0179_)
  );
  OAI21_X1 _0925_ (
    .A(_0068_),
    .B1(_0076_),
    .B2(rx_pkt_n[63]),
    .ZN(_0180_)
  );
  AOI21_X1 _0926_ (
    .A(_0180_),
    .B1(_0179_),
    .B2(_0178_),
    .ZN(clause_rx_ptr[49])
  );
  AOI222_X1 _0927_ (
    .A1(rx_pkt_w[64]),
    .A2(_0072_),
    .B1(_0074_),
    .B2(rx_pkt_e[64]),
    .C1(rx_pkt_s[64]),
    .C2(_0069_),
    .ZN(_0181_)
  );
  OAI21_X1 _0928_ (
    .A(_0068_),
    .B1(_0076_),
    .B2(rx_pkt_n[64]),
    .ZN(_0182_)
  );
  AOI21_X1 _0929_ (
    .A(_0182_),
    .B1(_0181_),
    .B2(_0076_),
    .ZN(clause_rx_ptr[50])
  );
  NAND2_X1 _0930_ (
    .A1(rx_pkt_w[65]),
    .A2(_0072_),
    .ZN(_0183_)
  );
  AOI221_X1 _0931_ (
    .A(_0075_),
    .B1(_0069_),
    .B2(rx_pkt_s[65]),
    .C1(rx_pkt_e[65]),
    .C2(_0074_),
    .ZN(_0184_)
  );
  OAI21_X1 _0932_ (
    .A(_0068_),
    .B1(_0076_),
    .B2(rx_pkt_n[65]),
    .ZN(_0185_)
  );
  AOI21_X1 _0933_ (
    .A(_0185_),
    .B1(_0184_),
    .B2(_0183_),
    .ZN(clause_rx_ptr[51])
  );
  NAND2_X1 _0934_ (
    .A1(rx_pkt_w[66]),
    .A2(_0072_),
    .ZN(_0186_)
  );
  AOI221_X1 _0935_ (
    .A(_0075_),
    .B1(_0069_),
    .B2(rx_pkt_s[66]),
    .C1(rx_pkt_e[66]),
    .C2(_0074_),
    .ZN(_0187_)
  );
  OAI21_X1 _0936_ (
    .A(_0068_),
    .B1(_0076_),
    .B2(rx_pkt_n[66]),
    .ZN(_0188_)
  );
  AOI21_X1 _0937_ (
    .A(_0188_),
    .B1(_0187_),
    .B2(_0186_),
    .ZN(clause_rx_ptr[52])
  );
  AOI222_X1 _0938_ (
    .A1(rx_pkt_w[67]),
    .A2(_0072_),
    .B1(_0074_),
    .B2(rx_pkt_e[67]),
    .C1(rx_pkt_s[67]),
    .C2(_0069_),
    .ZN(_0189_)
  );
  OAI21_X1 _0939_ (
    .A(_0068_),
    .B1(_0076_),
    .B2(rx_pkt_n[67]),
    .ZN(_0190_)
  );
  AOI21_X1 _0940_ (
    .A(_0190_),
    .B1(_0189_),
    .B2(_0076_),
    .ZN(clause_rx_ptr[53])
  );
  AOI222_X1 _0941_ (
    .A1(rx_pkt_w[68]),
    .A2(_0072_),
    .B1(_0074_),
    .B2(rx_pkt_e[68]),
    .C1(rx_pkt_s[68]),
    .C2(_0069_),
    .ZN(_0191_)
  );
  OAI21_X1 _0942_ (
    .A(_0068_),
    .B1(_0076_),
    .B2(rx_pkt_n[68]),
    .ZN(_0192_)
  );
  AOI21_X1 _0943_ (
    .A(_0192_),
    .B1(_0191_),
    .B2(_0076_),
    .ZN(clause_rx_ptr[54])
  );
  NAND2_X1 _0944_ (
    .A1(rx_pkt_w[69]),
    .A2(_0072_),
    .ZN(_0193_)
  );
  AOI221_X1 _0945_ (
    .A(_0075_),
    .B1(_0069_),
    .B2(rx_pkt_s[69]),
    .C1(rx_pkt_e[69]),
    .C2(_0074_),
    .ZN(_0194_)
  );
  OAI21_X1 _0946_ (
    .A(_0068_),
    .B1(_0076_),
    .B2(rx_pkt_n[69]),
    .ZN(_0195_)
  );
  AOI21_X1 _0947_ (
    .A(_0195_),
    .B1(_0194_),
    .B2(_0193_),
    .ZN(clause_rx_ptr[55])
  );
  AOI222_X1 _0948_ (
    .A1(rx_pkt_w[70]),
    .A2(_0072_),
    .B1(_0074_),
    .B2(rx_pkt_e[70]),
    .C1(rx_pkt_s[70]),
    .C2(_0069_),
    .ZN(_0196_)
  );
  OAI21_X1 _0949_ (
    .A(_0068_),
    .B1(_0076_),
    .B2(rx_pkt_n[70]),
    .ZN(_0197_)
  );
  AOI21_X1 _0950_ (
    .A(_0197_),
    .B1(_0196_),
    .B2(_0076_),
    .ZN(clause_rx_ptr[56])
  );
  AOI222_X1 _0951_ (
    .A1(rx_pkt_w[71]),
    .A2(_0072_),
    .B1(_0074_),
    .B2(rx_pkt_e[71]),
    .C1(rx_pkt_s[71]),
    .C2(_0069_),
    .ZN(_0198_)
  );
  OAI21_X1 _0952_ (
    .A(_0068_),
    .B1(_0076_),
    .B2(rx_pkt_n[71]),
    .ZN(_0199_)
  );
  AOI21_X1 _0953_ (
    .A(_0199_),
    .B1(_0198_),
    .B2(_0076_),
    .ZN(clause_rx_ptr[57])
  );
  NAND2_X1 _0954_ (
    .A1(rx_pkt_w[72]),
    .A2(_0072_),
    .ZN(_0200_)
  );
  AOI221_X1 _0955_ (
    .A(_0075_),
    .B1(_0069_),
    .B2(rx_pkt_s[72]),
    .C1(rx_pkt_e[72]),
    .C2(_0074_),
    .ZN(_0201_)
  );
  OAI21_X1 _0956_ (
    .A(_0068_),
    .B1(_0076_),
    .B2(rx_pkt_n[72]),
    .ZN(_0202_)
  );
  AOI21_X1 _0957_ (
    .A(_0202_),
    .B1(_0201_),
    .B2(_0200_),
    .ZN(clause_rx_ptr[58])
  );
  AOI222_X1 _0958_ (
    .A1(rx_pkt_w[73]),
    .A2(_0072_),
    .B1(_0074_),
    .B2(rx_pkt_e[73]),
    .C1(rx_pkt_s[73]),
    .C2(_0069_),
    .ZN(_0203_)
  );
  OAI21_X1 _0959_ (
    .A(_0068_),
    .B1(_0076_),
    .B2(rx_pkt_n[73]),
    .ZN(_0204_)
  );
  AOI21_X1 _0960_ (
    .A(_0204_),
    .B1(_0203_),
    .B2(_0076_),
    .ZN(clause_rx_ptr[59])
  );
  AOI222_X1 _0961_ (
    .A1(rx_pkt_w[74]),
    .A2(_0072_),
    .B1(_0074_),
    .B2(rx_pkt_e[74]),
    .C1(rx_pkt_s[74]),
    .C2(_0069_),
    .ZN(_0205_)
  );
  OAI21_X1 _0962_ (
    .A(_0068_),
    .B1(_0076_),
    .B2(rx_pkt_n[74]),
    .ZN(_0206_)
  );
  AOI21_X1 _0963_ (
    .A(_0206_),
    .B1(_0205_),
    .B2(_0076_),
    .ZN(clause_rx_ptr[60])
  );
  NAND2_X1 _0964_ (
    .A1(rx_pkt_w[75]),
    .A2(_0072_),
    .ZN(_0207_)
  );
  AOI221_X1 _0965_ (
    .A(_0075_),
    .B1(_0069_),
    .B2(rx_pkt_s[75]),
    .C1(rx_pkt_e[75]),
    .C2(_0074_),
    .ZN(_0208_)
  );
  OAI21_X1 _0966_ (
    .A(_0068_),
    .B1(_0076_),
    .B2(rx_pkt_n[75]),
    .ZN(_0209_)
  );
  AOI21_X1 _0967_ (
    .A(_0209_),
    .B1(_0208_),
    .B2(_0207_),
    .ZN(clause_rx_ptr[61])
  );
  AOI222_X1 _0968_ (
    .A1(rx_pkt_w[76]),
    .A2(_0072_),
    .B1(_0074_),
    .B2(rx_pkt_e[76]),
    .C1(rx_pkt_s[76]),
    .C2(_0069_),
    .ZN(_0210_)
  );
  OAI21_X1 _0969_ (
    .A(_0068_),
    .B1(_0076_),
    .B2(rx_pkt_n[76]),
    .ZN(_0211_)
  );
  AOI21_X1 _0970_ (
    .A(_0211_),
    .B1(_0210_),
    .B2(_0076_),
    .ZN(clause_rx_ptr[62])
  );
  AOI222_X1 _0971_ (
    .A1(rx_pkt_w[77]),
    .A2(_0072_),
    .B1(_0074_),
    .B2(rx_pkt_e[77]),
    .C1(rx_pkt_s[77]),
    .C2(_0069_),
    .ZN(_0212_)
  );
  OAI21_X1 _0972_ (
    .A(_0068_),
    .B1(_0076_),
    .B2(rx_pkt_n[77]),
    .ZN(_0213_)
  );
  AOI21_X1 _0973_ (
    .A(_0213_),
    .B1(_0212_),
    .B2(_0076_),
    .ZN(clause_rx_ptr[63])
  );
  NAND2_X1 _0974_ (
    .A1(rx_pkt_w[6]),
    .A2(_0072_),
    .ZN(_0214_)
  );
  AOI221_X1 _0975_ (
    .A(_0075_),
    .B1(_0069_),
    .B2(rx_pkt_s[6]),
    .C1(rx_pkt_e[6]),
    .C2(_0074_),
    .ZN(_0215_)
  );
  OAI21_X1 _0976_ (
    .A(_0068_),
    .B1(_0076_),
    .B2(rx_pkt_n[6]),
    .ZN(_0216_)
  );
  AOI21_X1 _0977_ (
    .A(_0216_),
    .B1(_0215_),
    .B2(_0214_),
    .ZN(clause_rx_lbd[0])
  );
  AOI222_X1 _0978_ (
    .A1(rx_pkt_w[7]),
    .A2(_0072_),
    .B1(_0074_),
    .B2(rx_pkt_e[7]),
    .C1(rx_pkt_s[7]),
    .C2(_0069_),
    .ZN(_0217_)
  );
  OAI21_X1 _0979_ (
    .A(_0068_),
    .B1(_0076_),
    .B2(rx_pkt_n[7]),
    .ZN(_0218_)
  );
  AOI21_X1 _0980_ (
    .A(_0218_),
    .B1(_0217_),
    .B2(_0076_),
    .ZN(clause_rx_lbd[1])
  );
  AOI222_X1 _0981_ (
    .A1(rx_pkt_w[8]),
    .A2(_0072_),
    .B1(_0074_),
    .B2(rx_pkt_e[8]),
    .C1(rx_pkt_s[8]),
    .C2(_0069_),
    .ZN(_0219_)
  );
  OAI21_X1 _0982_ (
    .A(_0068_),
    .B1(_0076_),
    .B2(rx_pkt_n[8]),
    .ZN(_0220_)
  );
  AOI21_X1 _0983_ (
    .A(_0220_),
    .B1(_0219_),
    .B2(_0076_),
    .ZN(clause_rx_lbd[2])
  );
  AOI222_X1 _0984_ (
    .A1(rx_pkt_w[9]),
    .A2(_0072_),
    .B1(_0074_),
    .B2(rx_pkt_e[9]),
    .C1(rx_pkt_s[9]),
    .C2(_0069_),
    .ZN(_0221_)
  );
  OAI21_X1 _0985_ (
    .A(_0068_),
    .B1(_0076_),
    .B2(rx_pkt_n[9]),
    .ZN(_0222_)
  );
  AOI21_X1 _0986_ (
    .A(_0222_),
    .B1(_0221_),
    .B2(_0076_),
    .ZN(clause_rx_lbd[3])
  );
  AOI222_X1 _0987_ (
    .A1(rx_pkt_w[10]),
    .A2(_0072_),
    .B1(_0074_),
    .B2(rx_pkt_e[10]),
    .C1(rx_pkt_s[10]),
    .C2(_0069_),
    .ZN(_0223_)
  );
  OAI21_X1 _0988_ (
    .A(_0068_),
    .B1(_0076_),
    .B2(rx_pkt_n[10]),
    .ZN(_0224_)
  );
  AOI21_X1 _0989_ (
    .A(_0224_),
    .B1(_0223_),
    .B2(_0076_),
    .ZN(clause_rx_lbd[4])
  );
  AOI222_X1 _0990_ (
    .A1(rx_pkt_w[11]),
    .A2(_0072_),
    .B1(_0074_),
    .B2(rx_pkt_e[11]),
    .C1(rx_pkt_s[11]),
    .C2(_0069_),
    .ZN(_0225_)
  );
  OAI21_X1 _0991_ (
    .A(_0068_),
    .B1(_0076_),
    .B2(rx_pkt_n[11]),
    .ZN(_0226_)
  );
  AOI21_X1 _0992_ (
    .A(_0226_),
    .B1(_0225_),
    .B2(_0076_),
    .ZN(clause_rx_lbd[5])
  );
  AOI222_X1 _0993_ (
    .A1(rx_pkt_w[12]),
    .A2(_0072_),
    .B1(_0074_),
    .B2(rx_pkt_e[12]),
    .C1(rx_pkt_s[12]),
    .C2(_0069_),
    .ZN(_0227_)
  );
  OAI21_X1 _0994_ (
    .A(_0068_),
    .B1(_0076_),
    .B2(rx_pkt_n[12]),
    .ZN(_0228_)
  );
  AOI21_X1 _0995_ (
    .A(_0228_),
    .B1(_0227_),
    .B2(_0076_),
    .ZN(clause_rx_lbd[6])
  );
  NAND2_X1 _0996_ (
    .A1(rx_pkt_w[13]),
    .A2(_0072_),
    .ZN(_0229_)
  );
  AOI221_X1 _0997_ (
    .A(_0075_),
    .B1(_0069_),
    .B2(rx_pkt_s[13]),
    .C1(rx_pkt_e[13]),
    .C2(_0074_),
    .ZN(_0230_)
  );
  OAI21_X1 _0998_ (
    .A(_0068_),
    .B1(_0076_),
    .B2(rx_pkt_n[13]),
    .ZN(_0231_)
  );
  AOI21_X1 _0999_ (
    .A(_0231_),
    .B1(_0230_),
    .B2(_0229_),
    .ZN(clause_rx_lbd[7])
  );
  AND3_X1 _1000_ (
    .A1(_0070_),
    .A2(_0071_),
    .A3(_0076_),
    .ZN(_0232_)
  );
  AOI21_X1 _1001_ (
    .A(force_valid),
    .B1(_0232_),
    .B2(_0359_),
    .ZN(clause_rx_valid)
  );
  OAI21_X1 _1002_ (
    .A(_0358_),
    .B1(_0232_),
    .B2(_0237_),
    .ZN(_0233_)
  );
  NOR3_X1 _1003_ (
    .A1(_0361_),
    .A2(_0002_),
    .A3(_0233_),
    .ZN(rx_ready_w)
  );
  NOR2_X1 _1004_ (
    .A1(_0360_),
    .A2(_0075_),
    .ZN(_0234_)
  );
  AOI21_X1 _1005_ (
    .A(_0361_),
    .B1(_0074_),
    .B2(_0234_),
    .ZN(_0235_)
  );
  NOR2_X1 _1006_ (
    .A1(_0002_),
    .A2(_0235_),
    .ZN(rx_ready_e)
  );
  NAND4_X1 _1007_ (
    .A1(_0239_),
    .A2(rx_valid_s),
    .A3(_0000_),
    .A4(_0234_),
    .ZN(_0236_)
  );
  AOI21_X1 _1008_ (
    .A(_0355_),
    .B1(_0356_),
    .B2(_0236_),
    .ZN(rx_ready_s)
  );
  assign clause_rx_fifo_lbd = clause_rx_lbd;
  assign clause_rx_fifo_ptr = clause_rx_ptr;
  assign clause_rx_fifo_valid = clause_rx_valid;
  assign diverge_rx_lit = force_lit;
  assign diverge_rx_valid = force_valid;
  assign neighbor_status = { rx_valid_n, rx_valid_s, rx_valid_e, rx_valid_w };
  assign { tx_pkt_e[79], tx_pkt_e[5:0] } = 7'h00;
  assign { tx_pkt_n[79:46], tx_pkt_n[13:0] } = { 1'h0, tx_pkt_e[78:46], tx_pkt_e[13:6], 6'h00 };
  assign { tx_pkt_s[79:46], tx_pkt_s[13:0] } = { 1'h0, tx_pkt_e[78:46], tx_pkt_e[13:6], 6'h00 };
  assign { tx_pkt_w[79:46], tx_pkt_w[13:0] } = { 1'h0, tx_pkt_e[78:46], tx_pkt_e[13:6], 6'h00 };
endmodule
