/* Generated by Yosys 0.60 (git sha1 5bafeb77dc71e054fa331ab9efa613e6fb0a1c49, clang++ 17.0.0 -fPIC -O3) */

module resync_controller(clk, rst_n, start, trail_height, done, trail_rd_idx, trail_rd_var, trail_rd_value, clear_shadows, fifo_flush, resync_valid, resync_var, resync_value);
  input clk;
  wire clk;
  input rst_n;
  wire rst_n;
  input start;
  wire start;
  input [15:0] trail_height;
  wire [15:0] trail_height;
  output done;
  wire done;
  output [15:0] trail_rd_idx;
  wire [15:0] trail_rd_idx;
  input [31:0] trail_rd_var;
  wire [31:0] trail_rd_var;
  input trail_rd_value;
  wire trail_rd_value;
  output clear_shadows;
  wire clear_shadows;
  output fifo_flush;
  wire fifo_flush;
  output resync_valid;
  wire resync_valid;
  output [31:0] resync_var;
  wire [31:0] resync_var;
  output resync_value;
  wire resync_value;
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire [15:0] _134_;
  wire [15:0] idx_q;
  wire [1:0] state_q;
  INV_X1 _135_ (
    .A(idx_q[0]),
    .ZN(_079_)
  );
  INV_X1 _136_ (
    .A(idx_q[1]),
    .ZN(_080_)
  );
  INV_X1 _137_ (
    .A(idx_q[2]),
    .ZN(_081_)
  );
  INV_X1 _138_ (
    .A(idx_q[3]),
    .ZN(_082_)
  );
  INV_X1 _139_ (
    .A(idx_q[5]),
    .ZN(_083_)
  );
  INV_X1 _140_ (
    .A(idx_q[8]),
    .ZN(_084_)
  );
  INV_X1 _141_ (
    .A(idx_q[9]),
    .ZN(_085_)
  );
  INV_X1 _142_ (
    .A(idx_q[10]),
    .ZN(_086_)
  );
  INV_X1 _143_ (
    .A(idx_q[12]),
    .ZN(_087_)
  );
  INV_X1 _144_ (
    .A(idx_q[13]),
    .ZN(_088_)
  );
  INV_X1 _145_ (
    .A(idx_q[14]),
    .ZN(_089_)
  );
  INV_X1 _146_ (
    .A(idx_q[15]),
    .ZN(_090_)
  );
  INV_X1 _147_ (
    .A(trail_height[2]),
    .ZN(_091_)
  );
  INV_X1 _148_ (
    .A(trail_height[4]),
    .ZN(_092_)
  );
  INV_X1 _149_ (
    .A(trail_height[6]),
    .ZN(_093_)
  );
  INV_X1 _150_ (
    .A(trail_height[7]),
    .ZN(_094_)
  );
  INV_X1 _151_ (
    .A(trail_height[10]),
    .ZN(_095_)
  );
  INV_X1 _152_ (
    .A(trail_height[11]),
    .ZN(_096_)
  );
  INV_X1 _153_ (
    .A(trail_height[14]),
    .ZN(_097_)
  );
  NOR2_X1 _154_ (
    .A1(_083_),
    .A2(trail_height[5]),
    .ZN(_098_)
  );
  OAI211_X1 _155_ (
    .A(_079_),
    .B(trail_height[0]),
    .C1(trail_height[1]),
    .C2(_080_),
    .ZN(_099_)
  );
  AOI22_X1 _156_ (
    .A1(idx_q[2]),
    .A2(_091_),
    .B1(trail_height[3]),
    .B2(_082_),
    .ZN(_100_)
  );
  AOI22_X1 _157_ (
    .A1(_080_),
    .A2(trail_height[1]),
    .B1(trail_height[2]),
    .B2(_081_),
    .ZN(_101_)
  );
  NAND3_X1 _158_ (
    .A1(_099_),
    .A2(_100_),
    .A3(_101_),
    .ZN(_102_)
  );
  AOI211_X1 _159_ (
    .A(_081_),
    .B(trail_height[2]),
    .C1(trail_height[3]),
    .C2(_082_),
    .ZN(_103_)
  );
  NOR2_X1 _160_ (
    .A1(_082_),
    .A2(trail_height[3]),
    .ZN(_104_)
  );
  AOI211_X1 _161_ (
    .A(_103_),
    .B(_104_),
    .C1(idx_q[4]),
    .C2(_092_),
    .ZN(_105_)
  );
  NOR2_X1 _162_ (
    .A1(idx_q[4]),
    .A2(_092_),
    .ZN(_106_)
  );
  AOI221_X1 _163_ (
    .A(_106_),
    .B1(_105_),
    .B2(_102_),
    .C1(_083_),
    .C2(trail_height[5]),
    .ZN(_107_)
  );
  OAI22_X1 _164_ (
    .A1(idx_q[6]),
    .A2(_093_),
    .B1(_098_),
    .B2(_107_),
    .ZN(_108_)
  );
  AOI22_X1 _165_ (
    .A1(idx_q[6]),
    .A2(_093_),
    .B1(_094_),
    .B2(idx_q[7]),
    .ZN(_109_)
  );
  AOI22_X1 _166_ (
    .A1(idx_q[10]),
    .A2(_095_),
    .B1(_096_),
    .B2(idx_q[11]),
    .ZN(_110_)
  );
  NOR2_X1 _167_ (
    .A1(idx_q[11]),
    .A2(_096_),
    .ZN(_111_)
  );
  NAND2_X1 _168_ (
    .A1(_086_),
    .A2(trail_height[10]),
    .ZN(_112_)
  );
  OAI211_X1 _169_ (
    .A(_110_),
    .B(_112_),
    .C1(idx_q[11]),
    .C2(_096_),
    .ZN(_113_)
  );
  NOR2_X1 _170_ (
    .A1(_085_),
    .A2(trail_height[9]),
    .ZN(_114_)
  );
  NOR2_X1 _171_ (
    .A1(idx_q[7]),
    .A2(_094_),
    .ZN(_115_)
  );
  NAND2_X1 _172_ (
    .A1(_085_),
    .A2(trail_height[9]),
    .ZN(_116_)
  );
  NOR2_X1 _173_ (
    .A1(_084_),
    .A2(trail_height[8]),
    .ZN(_117_)
  );
  NOR4_X1 _174_ (
    .A1(_113_),
    .A2(_114_),
    .A3(_115_),
    .A4(_117_),
    .ZN(_118_)
  );
  NAND2_X1 _175_ (
    .A1(_116_),
    .A2(_118_),
    .ZN(_020_)
  );
  AOI221_X1 _176_ (
    .A(_020_),
    .B1(_109_),
    .B2(_108_),
    .C1(_084_),
    .C2(trail_height[8]),
    .ZN(_021_)
  );
  AOI21_X1 _177_ (
    .A(_114_),
    .B1(_116_),
    .B2(_117_),
    .ZN(_022_)
  );
  OAI22_X1 _178_ (
    .A1(_110_),
    .A2(_111_),
    .B1(_113_),
    .B2(_022_),
    .ZN(_023_)
  );
  OAI22_X1 _179_ (
    .A1(_089_),
    .A2(trail_height[14]),
    .B1(trail_height[15]),
    .B2(_090_),
    .ZN(_024_)
  );
  NAND2_X1 _180_ (
    .A1(_090_),
    .A2(trail_height[15]),
    .ZN(_025_)
  );
  OAI21_X1 _181_ (
    .A(_025_),
    .B1(_097_),
    .B2(idx_q[14]),
    .ZN(_026_)
  );
  OR2_X1 _182_ (
    .A1(_024_),
    .A2(_026_),
    .ZN(_027_)
  );
  NOR2_X1 _183_ (
    .A1(_088_),
    .A2(trail_height[13]),
    .ZN(_028_)
  );
  AOI21_X1 _184_ (
    .A(_028_),
    .B1(trail_height[12]),
    .B2(_087_),
    .ZN(_029_)
  );
  NAND2_X1 _185_ (
    .A1(_088_),
    .A2(trail_height[13]),
    .ZN(_030_)
  );
  NOR2_X1 _186_ (
    .A1(_087_),
    .A2(trail_height[12]),
    .ZN(_031_)
  );
  AOI211_X1 _187_ (
    .A(_027_),
    .B(_031_),
    .C1(_088_),
    .C2(trail_height[13]),
    .ZN(_032_)
  );
  OAI211_X1 _188_ (
    .A(_029_),
    .B(_032_),
    .C1(_021_),
    .C2(_023_),
    .ZN(_033_)
  );
  AOI21_X1 _189_ (
    .A(_028_),
    .B1(_030_),
    .B2(_031_),
    .ZN(_034_)
  );
  NOR2_X1 _190_ (
    .A1(_027_),
    .A2(_034_),
    .ZN(_035_)
  );
  AOI21_X1 _191_ (
    .A(_035_),
    .B1(_025_),
    .B2(_024_),
    .ZN(_036_)
  );
  AND2_X1 _192_ (
    .A1(_033_),
    .A2(_036_),
    .ZN(_037_)
  );
  NOR2_X1 _193_ (
    .A1(state_q[0]),
    .A2(_000_),
    .ZN(_038_)
  );
  NAND2_X1 _194_ (
    .A1(_037_),
    .A2(_038_),
    .ZN(_039_)
  );
  INV_X1 _195_ (
    .A(_039_),
    .ZN(resync_valid)
  );
  OR2_X1 _196_ (
    .A1(state_q[0]),
    .A2(state_q[1]),
    .ZN(_040_)
  );
  OAI21_X1 _197_ (
    .A(_039_),
    .B1(_040_),
    .B2(start),
    .ZN(_041_)
  );
  AOI211_X1 _198_ (
    .A(state_q[0]),
    .B(_041_),
    .C1(_000_),
    .C2(state_q[1]),
    .ZN(_002_)
  );
  NOR2_X1 _199_ (
    .A1(state_q[1]),
    .A2(_001_),
    .ZN(clear_shadows)
  );
  NOR2_X1 _200_ (
    .A1(_038_),
    .A2(clear_shadows),
    .ZN(_042_)
  );
  AOI211_X1 _201_ (
    .A(state_q[0]),
    .B(_000_),
    .C1(_033_),
    .C2(_036_),
    .ZN(_043_)
  );
  NAND2_X1 _202_ (
    .A1(state_q[1]),
    .A2(resync_valid),
    .ZN(_044_)
  );
  OAI21_X1 _203_ (
    .A(_044_),
    .B1(_042_),
    .B2(_041_),
    .ZN(_003_)
  );
  NOR2_X1 _204_ (
    .A1(_001_),
    .A2(_000_),
    .ZN(done)
  );
  OAI21_X1 _205_ (
    .A(_040_),
    .B1(_000_),
    .B2(_001_),
    .ZN(_045_)
  );
  NOR2_X1 _206_ (
    .A1(_038_),
    .A2(_045_),
    .ZN(_046_)
  );
  OR2_X1 _207_ (
    .A1(_038_),
    .A2(_045_),
    .ZN(_047_)
  );
  NOR2_X1 _208_ (
    .A1(_043_),
    .A2(_045_),
    .ZN(_048_)
  );
  NAND3_X1 _209_ (
    .A1(_134_[0]),
    .A2(resync_valid),
    .A3(_048_),
    .ZN(_049_)
  );
  OAI21_X1 _210_ (
    .A(_049_),
    .B1(_048_),
    .B2(_079_),
    .ZN(_004_)
  );
  AOI21_X1 _211_ (
    .A(idx_q[1]),
    .B1(_048_),
    .B2(idx_q[0]),
    .ZN(_050_)
  );
  NAND2_X1 _212_ (
    .A1(idx_q[0]),
    .A2(idx_q[1]),
    .ZN(_051_)
  );
  NOR3_X1 _213_ (
    .A1(_043_),
    .A2(_045_),
    .A3(_051_),
    .ZN(_052_)
  );
  NOR3_X1 _214_ (
    .A1(_046_),
    .A2(_050_),
    .A3(_052_),
    .ZN(_005_)
  );
  OAI21_X1 _215_ (
    .A(_047_),
    .B1(_052_),
    .B2(idx_q[2]),
    .ZN(_053_)
  );
  AOI21_X1 _216_ (
    .A(_053_),
    .B1(_052_),
    .B2(idx_q[2]),
    .ZN(_006_)
  );
  NOR2_X1 _217_ (
    .A1(_081_),
    .A2(_082_),
    .ZN(_054_)
  );
  AOI21_X1 _218_ (
    .A(idx_q[3]),
    .B1(_052_),
    .B2(idx_q[2]),
    .ZN(_055_)
  );
  AOI211_X1 _219_ (
    .A(_046_),
    .B(_055_),
    .C1(_054_),
    .C2(_052_),
    .ZN(_007_)
  );
  AOI21_X1 _220_ (
    .A(idx_q[4]),
    .B1(_052_),
    .B2(_054_),
    .ZN(_056_)
  );
  NAND2_X1 _221_ (
    .A1(idx_q[4]),
    .A2(_054_),
    .ZN(_057_)
  );
  NOR4_X1 _222_ (
    .A1(_043_),
    .A2(_045_),
    .A3(_051_),
    .A4(_057_),
    .ZN(_058_)
  );
  NOR3_X1 _223_ (
    .A1(_046_),
    .A2(_056_),
    .A3(_058_),
    .ZN(_008_)
  );
  OAI21_X1 _224_ (
    .A(_047_),
    .B1(_058_),
    .B2(idx_q[5]),
    .ZN(_059_)
  );
  AOI21_X1 _225_ (
    .A(_059_),
    .B1(_058_),
    .B2(idx_q[5]),
    .ZN(_009_)
  );
  AND2_X1 _226_ (
    .A1(idx_q[5]),
    .A2(idx_q[6]),
    .ZN(_060_)
  );
  AOI21_X1 _227_ (
    .A(idx_q[6]),
    .B1(_058_),
    .B2(idx_q[5]),
    .ZN(_061_)
  );
  AOI211_X1 _228_ (
    .A(_046_),
    .B(_061_),
    .C1(_060_),
    .C2(_058_),
    .ZN(_010_)
  );
  AND3_X1 _229_ (
    .A1(idx_q[7]),
    .A2(_058_),
    .A3(_060_),
    .ZN(_062_)
  );
  AOI21_X1 _230_ (
    .A(idx_q[7]),
    .B1(_058_),
    .B2(_060_),
    .ZN(_063_)
  );
  NOR3_X1 _231_ (
    .A1(_046_),
    .A2(_062_),
    .A3(_063_),
    .ZN(_011_)
  );
  AND3_X1 _232_ (
    .A1(idx_q[7]),
    .A2(idx_q[8]),
    .A3(_060_),
    .ZN(_064_)
  );
  AND2_X1 _233_ (
    .A1(_058_),
    .A2(_064_),
    .ZN(_065_)
  );
  OAI21_X1 _234_ (
    .A(_047_),
    .B1(_062_),
    .B2(idx_q[8]),
    .ZN(_066_)
  );
  NOR2_X1 _235_ (
    .A1(_065_),
    .A2(_066_),
    .ZN(_012_)
  );
  OAI21_X1 _236_ (
    .A(_047_),
    .B1(_065_),
    .B2(idx_q[9]),
    .ZN(_067_)
  );
  AOI21_X1 _237_ (
    .A(_067_),
    .B1(_065_),
    .B2(idx_q[9]),
    .ZN(_013_)
  );
  AOI21_X1 _238_ (
    .A(idx_q[10]),
    .B1(_065_),
    .B2(idx_q[9]),
    .ZN(_068_)
  );
  NOR2_X1 _239_ (
    .A1(_085_),
    .A2(_086_),
    .ZN(_069_)
  );
  AOI211_X1 _240_ (
    .A(_046_),
    .B(_068_),
    .C1(_069_),
    .C2(_065_),
    .ZN(_014_)
  );
  AOI21_X1 _241_ (
    .A(idx_q[11]),
    .B1(_065_),
    .B2(_069_),
    .ZN(_070_)
  );
  AND3_X1 _242_ (
    .A1(idx_q[11]),
    .A2(_064_),
    .A3(_069_),
    .ZN(_071_)
  );
  AND2_X1 _243_ (
    .A1(_058_),
    .A2(_071_),
    .ZN(_072_)
  );
  NOR3_X1 _244_ (
    .A1(_046_),
    .A2(_070_),
    .A3(_072_),
    .ZN(_015_)
  );
  NAND3_X1 _245_ (
    .A1(idx_q[12]),
    .A2(_058_),
    .A3(_071_),
    .ZN(_073_)
  );
  OAI21_X1 _246_ (
    .A(_047_),
    .B1(_072_),
    .B2(idx_q[12]),
    .ZN(_074_)
  );
  AOI21_X1 _247_ (
    .A(_074_),
    .B1(_072_),
    .B2(idx_q[12]),
    .ZN(_016_)
  );
  NAND4_X1 _248_ (
    .A1(idx_q[12]),
    .A2(idx_q[13]),
    .A3(_058_),
    .A4(_071_),
    .ZN(_075_)
  );
  NAND2_X1 _249_ (
    .A1(_088_),
    .A2(_073_),
    .ZN(_076_)
  );
  AND3_X1 _250_ (
    .A1(_047_),
    .A2(_075_),
    .A3(_076_),
    .ZN(_017_)
  );
  OR2_X1 _251_ (
    .A1(_089_),
    .A2(_075_),
    .ZN(_077_)
  );
  AOI21_X1 _252_ (
    .A(_046_),
    .B1(_075_),
    .B2(_089_),
    .ZN(_078_)
  );
  AND2_X1 _253_ (
    .A1(_077_),
    .A2(_078_),
    .ZN(_018_)
  );
  AOI21_X1 _254_ (
    .A(_046_),
    .B1(_077_),
    .B2(_090_),
    .ZN(_019_)
  );
  DFFR_X1 _255_ (
    .CK(clk),
    .D(_002_),
    .Q(state_q[0]),
    .QN(_001_),
    .RN(rst_n)
  );
  DFFR_X1 _256_ (
    .CK(clk),
    .D(_003_),
    .Q(state_q[1]),
    .QN(_000_),
    .RN(rst_n)
  );
  DFFR_X1 _257_ (
    .CK(clk),
    .D(_004_),
    .Q(idx_q[0]),
    .QN(_134_[0]),
    .RN(rst_n)
  );
  DFFR_X1 _258_ (
    .CK(clk),
    .D(_005_),
    .Q(idx_q[1]),
    .QN(_123_),
    .RN(rst_n)
  );
  DFFR_X1 _259_ (
    .CK(clk),
    .D(_006_),
    .Q(idx_q[2]),
    .QN(_122_),
    .RN(rst_n)
  );
  DFFR_X1 _260_ (
    .CK(clk),
    .D(_007_),
    .Q(idx_q[3]),
    .QN(_121_),
    .RN(rst_n)
  );
  DFFR_X1 _261_ (
    .CK(clk),
    .D(_008_),
    .Q(idx_q[4]),
    .QN(_120_),
    .RN(rst_n)
  );
  DFFR_X1 _262_ (
    .CK(clk),
    .D(_009_),
    .Q(idx_q[5]),
    .QN(_119_),
    .RN(rst_n)
  );
  DFFR_X1 _263_ (
    .CK(clk),
    .D(_010_),
    .Q(idx_q[6]),
    .QN(_133_),
    .RN(rst_n)
  );
  DFFR_X1 _264_ (
    .CK(clk),
    .D(_011_),
    .Q(idx_q[7]),
    .QN(_132_),
    .RN(rst_n)
  );
  DFFR_X1 _265_ (
    .CK(clk),
    .D(_012_),
    .Q(idx_q[8]),
    .QN(_131_),
    .RN(rst_n)
  );
  DFFR_X1 _266_ (
    .CK(clk),
    .D(_013_),
    .Q(idx_q[9]),
    .QN(_130_),
    .RN(rst_n)
  );
  DFFR_X1 _267_ (
    .CK(clk),
    .D(_014_),
    .Q(idx_q[10]),
    .QN(_129_),
    .RN(rst_n)
  );
  DFFR_X1 _268_ (
    .CK(clk),
    .D(_015_),
    .Q(idx_q[11]),
    .QN(_128_),
    .RN(rst_n)
  );
  DFFR_X1 _269_ (
    .CK(clk),
    .D(_016_),
    .Q(idx_q[12]),
    .QN(_127_),
    .RN(rst_n)
  );
  DFFR_X1 _270_ (
    .CK(clk),
    .D(_017_),
    .Q(idx_q[13]),
    .QN(_126_),
    .RN(rst_n)
  );
  DFFR_X1 _271_ (
    .CK(clk),
    .D(_018_),
    .Q(idx_q[14]),
    .QN(_125_),
    .RN(rst_n)
  );
  DFFR_X1 _272_ (
    .CK(clk),
    .D(_019_),
    .Q(idx_q[15]),
    .QN(_124_),
    .RN(rst_n)
  );
  assign _134_[15:1] = idx_q[15:1];
  assign fifo_flush = clear_shadows;
  assign resync_value = trail_rd_value;
  assign resync_var = trail_rd_var;
  assign trail_rd_idx = idx_q;
endmodule
