// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Design internal header
// See Vtb_hw_bench.h for the primary calling header

#ifndef VERILATED_VTB_HW_BENCH___024ROOT_H_
#define VERILATED_VTB_HW_BENCH___024ROOT_H_  // guard

#include "verilated.h"
#include "verilated_timing.h"


class Vtb_hw_bench__Syms;

class alignas(VL_CACHE_LINE_BYTES) Vtb_hw_bench___024root final {
  public:

    // DESIGN SPECIFIC STATE
    // Anonymous structures to workaround compiler member-count bugs
    struct {
        CData/*0:0*/ tb_hw_bench__DOT__clk;
        CData/*0:0*/ tb_hw_bench__DOT__rst_n;
        CData/*0:0*/ tb_hw_bench__DOT__start_solve;
        CData/*0:0*/ tb_hw_bench__DOT__solve_done;
        CData/*0:0*/ tb_hw_bench__DOT__is_sat;
        CData/*0:0*/ tb_hw_bench__DOT__is_unsat;
        CData/*0:0*/ tb_hw_bench__DOT__load_valid;
        CData/*0:0*/ tb_hw_bench__DOT__load_clause_end;
        CData/*0:0*/ tb_hw_bench__DOT__load_ready;
        CData/*4:0*/ tb_hw_bench__DOT__dut__DOT__state_q;
        CData/*4:0*/ tb_hw_bench__DOT__dut__DOT__state_d;
        CData/*3:0*/ tb_hw_bench__DOT__dut__DOT__prop_count_q;
        CData/*3:0*/ tb_hw_bench__DOT__dut__DOT__prop_count_d;
        CData/*0:0*/ tb_hw_bench__DOT__dut__DOT__conflict_seen_q;
        CData/*0:0*/ tb_hw_bench__DOT__dut__DOT__conflict_seen_d;
        CData/*0:0*/ tb_hw_bench__DOT__dut__DOT__resync_started_q;
        CData/*0:0*/ tb_hw_bench__DOT__dut__DOT__resync_started_d;
        CData/*0:0*/ tb_hw_bench__DOT__dut__DOT__pse_started_q;
        CData/*0:0*/ tb_hw_bench__DOT__dut__DOT__pse_started_d;
        CData/*0:0*/ tb_hw_bench__DOT__dut__DOT__last_decision_phase_q;
        CData/*0:0*/ tb_hw_bench__DOT__dut__DOT__last_decision_phase_d;
        CData/*0:0*/ tb_hw_bench__DOT__dut__DOT__tried_both_phases_q;
        CData/*0:0*/ tb_hw_bench__DOT__dut__DOT__tried_both_phases_d;
        CData/*0:0*/ tb_hw_bench__DOT__dut__DOT__verify_mode_q;
        CData/*0:0*/ tb_hw_bench__DOT__dut__DOT__verify_mode_d;
        CData/*0:0*/ tb_hw_bench__DOT__dut__DOT__restart_pending_q;
        CData/*0:0*/ tb_hw_bench__DOT__dut__DOT__restart_pending_d;
        CData/*3:0*/ tb_hw_bench__DOT__dut__DOT__query_index_q;
        CData/*3:0*/ tb_hw_bench__DOT__dut__DOT__query_index_d;
        CData/*0:0*/ tb_hw_bench__DOT__dut__DOT__trail_push;
        CData/*0:0*/ tb_hw_bench__DOT__dut__DOT__trail_push_value;
        CData/*0:0*/ tb_hw_bench__DOT__dut__DOT__trail_push_is_decision;
        CData/*0:0*/ tb_hw_bench__DOT__dut__DOT__trail_backtrack_done;
        CData/*0:0*/ tb_hw_bench__DOT__dut__DOT__trail_backtrack_valid;
        CData/*0:0*/ tb_hw_bench__DOT__dut__DOT__trail_backtrack_value;
        CData/*0:0*/ tb_hw_bench__DOT__dut__DOT__trail_backtrack_is_decision;
        CData/*0:0*/ tb_hw_bench__DOT__dut__DOT__trail_query_valid;
        CData/*0:0*/ tb_hw_bench__DOT__dut__DOT__trail_query_value;
        CData/*0:0*/ tb_hw_bench__DOT__dut__DOT__trail_clear_all;
        CData/*0:0*/ tb_hw_bench__DOT__dut__DOT__pse_start;
        CData/*0:0*/ tb_hw_bench__DOT__dut__DOT__pse_done;
        CData/*0:0*/ tb_hw_bench__DOT__dut__DOT__pse_conflict;
        CData/*0:0*/ tb_hw_bench__DOT__dut__DOT__pse_propagated_valid;
        CData/*0:0*/ tb_hw_bench__DOT__dut__DOT__pse_clear_assignments;
        CData/*3:0*/ tb_hw_bench__DOT__dut__DOT__pse_conflict_clause_len;
        CData/*0:0*/ tb_hw_bench__DOT__dut__DOT__pse_assign_broadcast_valid;
        CData/*0:0*/ tb_hw_bench__DOT__dut__DOT__pse_assign_broadcast_value;
        CData/*3:0*/ tb_hw_bench__DOT__dut__DOT__conflict_clause_len_q;
        CData/*3:0*/ tb_hw_bench__DOT__dut__DOT__conflict_clause_len_d;
        CData/*3:0*/ tb_hw_bench__DOT__dut__DOT__learn_idx_q;
        CData/*3:0*/ tb_hw_bench__DOT__dut__DOT__learn_idx_d;
        CData/*0:0*/ tb_hw_bench__DOT__dut__DOT__cae_start;
        CData/*0:0*/ tb_hw_bench__DOT__dut__DOT__cae_done;
        CData/*3:0*/ tb_hw_bench__DOT__dut__DOT__cae_learned_len;
        CData/*7:0*/ tb_hw_bench__DOT__dut__DOT__cae_backtrack_level;
        CData/*0:0*/ tb_hw_bench__DOT__dut__DOT__vde_request;
        CData/*0:0*/ tb_hw_bench__DOT__dut__DOT__vde_decision_valid;
        CData/*0:0*/ tb_hw_bench__DOT__dut__DOT__vde_decision_phase;
        CData/*0:0*/ tb_hw_bench__DOT__dut__DOT__vde_all_assigned;
        CData/*0:0*/ tb_hw_bench__DOT__dut__DOT__vde_assign_valid;
        CData/*0:0*/ tb_hw_bench__DOT__dut__DOT__vde_assign_value;
        CData/*0:0*/ tb_hw_bench__DOT__dut__DOT__vde_clear_all;
        CData/*0:0*/ tb_hw_bench__DOT__dut__DOT__vde_clear_valid;
        CData/*3:0*/ tb_hw_bench__DOT__dut__DOT__vde_bump_count;
    };
    struct {
        CData/*0:0*/ tb_hw_bench__DOT__dut__DOT__vde_decay;
        CData/*0:0*/ tb_hw_bench__DOT__dut__DOT__unnamedblk5__DOT__prop_already_assigned;
        CData/*1:0*/ tb_hw_bench__DOT__dut__DOT__u_vde__DOT__state_q;
        CData/*1:0*/ tb_hw_bench__DOT__dut__DOT__u_vde__DOT__state_d;
        CData/*1:0*/ tb_hw_bench__DOT__dut__DOT__u_trail__DOT__bt_state_q;
        CData/*1:0*/ tb_hw_bench__DOT__dut__DOT__u_trail__DOT__bt_state_d;
        CData/*3:0*/ tb_hw_bench__DOT__dut__DOT__u_pse__DOT__state_q;
        CData/*3:0*/ tb_hw_bench__DOT__dut__DOT__u_pse__DOT__state_d;
        CData/*0:0*/ tb_hw_bench__DOT__dut__DOT__u_pse__DOT__scan_list_sel_q;
        CData/*0:0*/ tb_hw_bench__DOT__dut__DOT__u_pse__DOT__scan_list_sel_d;
        CData/*0:0*/ tb_hw_bench__DOT__dut__DOT__u_pse__DOT__assign_wr_en;
        CData/*1:0*/ tb_hw_bench__DOT__dut__DOT__u_pse__DOT__assign_wr_val;
        CData/*0:0*/ tb_hw_bench__DOT__dut__DOT__u_pse__DOT__prop_push;
        CData/*0:0*/ tb_hw_bench__DOT__dut__DOT__u_pse__DOT__load_fire;
        CData/*1:0*/ tb_hw_bench__DOT__dut__DOT__u_pse__DOT__unnamedblk1__DOT__other_truth;
        CData/*0:0*/ tb_hw_bench__DOT__dut__DOT__u_pse__DOT__unnamedblk1__DOT__found_repl;
        CData/*1:0*/ tb_hw_bench__DOT__dut__DOT__u_pse__DOT__unnamedblk1__DOT__t;
        CData/*1:0*/ tb_hw_bench__DOT__dut__DOT__u_cae__DOT__state_q;
        CData/*1:0*/ tb_hw_bench__DOT__dut__DOT__u_cae__DOT__state_d;
        CData/*3:0*/ tb_hw_bench__DOT__dut__DOT__u_cae__DOT__learned_count_q;
        CData/*3:0*/ tb_hw_bench__DOT__dut__DOT__u_cae__DOT__learned_count_d;
        CData/*7:0*/ tb_hw_bench__DOT__dut__DOT__u_cae__DOT__backtrack_q;
        CData/*7:0*/ tb_hw_bench__DOT__dut__DOT__u_cae__DOT__backtrack_d;
        CData/*0:0*/ tb_hw_bench__DOT__dut__DOT__u_cae__DOT__unsat_q;
        CData/*0:0*/ tb_hw_bench__DOT__dut__DOT__u_cae__DOT__unsat_d;
        CData/*7:0*/ tb_hw_bench__DOT__dut__DOT__u_cae__DOT__max_level;
        CData/*7:0*/ tb_hw_bench__DOT__dut__DOT__u_cae__DOT__used_mask;
        CData/*1:0*/ __Vfunc_tb_hw_bench__DOT__dut__DOT__u_pse__DOT__lit_truth__1__Vfuncout;
        CData/*1:0*/ __Vfunc_tb_hw_bench__DOT__dut__DOT__u_pse__DOT__lit_truth__2__Vfuncout;
        CData/*0:0*/ __Vtrigprevexpr___TOP__tb_hw_bench__DOT__dut__DOT__pse_start__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__tb_hw_bench__DOT__dut__DOT__pse_assign_broadcast_valid__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__tb_hw_bench__DOT__dut__DOT__pse_assign_broadcast_value__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__tb_hw_bench__DOT__dut__DOT__cae_start__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__tb_hw_bench__DOT__dut__DOT__trail_query_valid__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__tb_hw_bench__DOT__dut__DOT__trail_query_value__0;
        CData/*0:0*/ __VstlDidInit;
        CData/*0:0*/ __VstlFirstIteration;
        CData/*0:0*/ __Vtrigprevexpr___TOP__tb_hw_bench__DOT__dut__DOT__pse_start__1;
        CData/*0:0*/ __Vtrigprevexpr___TOP__tb_hw_bench__DOT__dut__DOT__pse_assign_broadcast_valid__1;
        CData/*0:0*/ __Vtrigprevexpr___TOP__tb_hw_bench__DOT__dut__DOT__pse_assign_broadcast_value__1;
        CData/*0:0*/ __Vtrigprevexpr___TOP__tb_hw_bench__DOT__dut__DOT__cae_start__1;
        CData/*0:0*/ __Vtrigprevexpr___TOP__tb_hw_bench__DOT__dut__DOT__trail_query_valid__1;
        CData/*0:0*/ __Vtrigprevexpr___TOP__tb_hw_bench__DOT__dut__DOT__trail_query_value__1;
        CData/*0:0*/ __Vtrigprevexpr___TOP__tb_hw_bench__DOT__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__tb_hw_bench__DOT__rst_n__0;
        CData/*0:0*/ __VactDidInit;
        SData/*15:0*/ tb_hw_bench__DOT__dut__DOT__cycle_count_q;
        SData/*15:0*/ tb_hw_bench__DOT__dut__DOT__cycle_count_d;
        SData/*15:0*/ tb_hw_bench__DOT__dut__DOT__decision_level_q;
        SData/*15:0*/ tb_hw_bench__DOT__dut__DOT__decision_level_d;
        SData/*15:0*/ tb_hw_bench__DOT__dut__DOT__level0_conflict_count_q;
        SData/*15:0*/ tb_hw_bench__DOT__dut__DOT__level0_conflict_count_d;
        SData/*15:0*/ tb_hw_bench__DOT__dut__DOT__conflict_counter_q;
        SData/*15:0*/ tb_hw_bench__DOT__dut__DOT__conflict_counter_d;
        SData/*15:0*/ tb_hw_bench__DOT__dut__DOT__restart_count_q;
        SData/*15:0*/ tb_hw_bench__DOT__dut__DOT__restart_count_d;
        SData/*15:0*/ tb_hw_bench__DOT__dut__DOT__trail_push_level;
        SData/*15:0*/ tb_hw_bench__DOT__dut__DOT__trail_query_level;
        SData/*15:0*/ tb_hw_bench__DOT__dut__DOT__u_vde__DOT__best_idx_q;
        SData/*15:0*/ tb_hw_bench__DOT__dut__DOT__u_vde__DOT__best_idx_d;
        SData/*15:0*/ tb_hw_bench__DOT__dut__DOT__u_vde__DOT__scan_idx_q;
        SData/*15:0*/ tb_hw_bench__DOT__dut__DOT__u_vde__DOT__scan_idx_d;
        SData/*15:0*/ tb_hw_bench__DOT__dut__DOT__u_trail__DOT__trail_height_q;
        SData/*15:0*/ tb_hw_bench__DOT__dut__DOT__u_trail__DOT__trail_height_d;
    };
    struct {
        SData/*15:0*/ tb_hw_bench__DOT__dut__DOT__u_trail__DOT__bt_index_q;
        SData/*15:0*/ tb_hw_bench__DOT__dut__DOT__u_trail__DOT__bt_index_d;
        SData/*15:0*/ tb_hw_bench__DOT__dut__DOT__u_trail__DOT__bt_target_q;
        SData/*15:0*/ tb_hw_bench__DOT__dut__DOT__u_trail__DOT__bt_target_d;
        SData/*15:0*/ tb_hw_bench__DOT__dut__DOT__u_pse__DOT____Vlvbound_h3fedabd8__0;
        SData/*15:0*/ tb_hw_bench__DOT__dut__DOT__u_pse__DOT____Vlvbound_hbcbfc3d7__0;
        SData/*15:0*/ tb_hw_bench__DOT__dut__DOT__u_pse__DOT____Vlvbound_h00d61c0b__1;
        SData/*15:0*/ tb_hw_bench__DOT__dut__DOT__u_pse__DOT____Vlvbound_h29b188f6__1;
        SData/*15:0*/ tb_hw_bench__DOT__dut__DOT__u_pse__DOT____Vlvbound_h40ce9c10__1;
        SData/*15:0*/ tb_hw_bench__DOT__dut__DOT__u_pse__DOT____Vlvbound_h604b715b__1;
        SData/*15:0*/ tb_hw_bench__DOT__dut__DOT__u_pse__DOT____Vlvbound_h00d61c0b__0;
        SData/*15:0*/ tb_hw_bench__DOT__dut__DOT__u_pse__DOT____Vlvbound_h29b188f6__0;
        SData/*15:0*/ tb_hw_bench__DOT__dut__DOT__u_pse__DOT____Vlvbound_h40ce9c10__0;
        SData/*15:0*/ tb_hw_bench__DOT__dut__DOT__u_pse__DOT____Vlvbound_h604b715b__0;
        SData/*15:0*/ tb_hw_bench__DOT__dut__DOT__u_pse__DOT____Vlvbound_hefbe1e22__0;
        SData/*15:0*/ tb_hw_bench__DOT__dut__DOT__u_pse__DOT____Vlvbound_hc8ff74ca__0;
        SData/*15:0*/ tb_hw_bench__DOT__dut__DOT__u_pse__DOT____Vlvbound_h89617ee6__0;
        SData/*15:0*/ tb_hw_bench__DOT__dut__DOT__u_pse__DOT____Vlvbound_h5838062a__0;
        SData/*15:0*/ tb_hw_bench__DOT__dut__DOT__u_pse__DOT____Vlvbound_hc7e6b68a__0;
        SData/*15:0*/ tb_hw_bench__DOT__dut__DOT__u_pse__DOT____Vlvbound_hcead6646__0;
        SData/*15:0*/ tb_hw_bench__DOT__dut__DOT__u_pse__DOT____Vlvbound_h1fa06947__0;
        SData/*15:0*/ tb_hw_bench__DOT__dut__DOT__u_pse__DOT____Vlvbound_h39167de9__0;
        SData/*15:0*/ tb_hw_bench__DOT__dut__DOT__u_pse__DOT____Vlvbound_h7f3f1653__0;
        SData/*15:0*/ tb_hw_bench__DOT__dut__DOT__u_pse__DOT____Vlvbound_h81e6d567__0;
        SData/*15:0*/ tb_hw_bench__DOT__dut__DOT__u_pse__DOT____Vlvbound_h38aa84f1__0;
        SData/*15:0*/ tb_hw_bench__DOT__dut__DOT__u_pse__DOT____Vlvbound_h0f6e9a5b__0;
        SData/*15:0*/ tb_hw_bench__DOT__dut__DOT__u_pse__DOT____Vlvbound_ha6773321__0;
        SData/*15:0*/ tb_hw_bench__DOT__dut__DOT__u_pse__DOT____Vlvbound_h68eec191__0;
        SData/*15:0*/ tb_hw_bench__DOT__dut__DOT__u_pse__DOT__prop_head_q;
        SData/*15:0*/ tb_hw_bench__DOT__dut__DOT__u_pse__DOT__prop_head_d;
        SData/*15:0*/ tb_hw_bench__DOT__dut__DOT__u_pse__DOT__prop_tail_q;
        SData/*15:0*/ tb_hw_bench__DOT__dut__DOT__u_pse__DOT__prop_tail_d;
        SData/*15:0*/ tb_hw_bench__DOT__dut__DOT__u_pse__DOT__clause_count_q;
        SData/*15:0*/ tb_hw_bench__DOT__dut__DOT__u_pse__DOT__clause_count_d;
        SData/*15:0*/ tb_hw_bench__DOT__dut__DOT__u_pse__DOT__lit_count_q;
        SData/*15:0*/ tb_hw_bench__DOT__dut__DOT__u_pse__DOT__lit_count_d;
        SData/*15:0*/ tb_hw_bench__DOT__dut__DOT__u_pse__DOT__cur_clause_len_q;
        SData/*15:0*/ tb_hw_bench__DOT__dut__DOT__u_pse__DOT__cur_clause_len_d;
        SData/*15:0*/ tb_hw_bench__DOT__dut__DOT__u_pse__DOT__init_clause_idx_q;
        SData/*15:0*/ tb_hw_bench__DOT__dut__DOT__u_pse__DOT__init_clause_idx_d;
        SData/*15:0*/ tb_hw_bench__DOT__dut__DOT__u_pse__DOT__scan_clause_q;
        SData/*15:0*/ tb_hw_bench__DOT__dut__DOT__u_pse__DOT__scan_clause_d;
        SData/*15:0*/ tb_hw_bench__DOT__dut__DOT__u_pse__DOT__scan_prev_q;
        SData/*15:0*/ tb_hw_bench__DOT__dut__DOT__u_pse__DOT__scan_prev_d;
        SData/*15:0*/ tb_hw_bench__DOT__dut__DOT__u_pse__DOT__assign_wr_idx;
        SData/*15:0*/ tb_hw_bench__DOT__dut__DOT__u_pse__DOT__unnamedblk1__DOT__idx;
        SData/*15:0*/ tb_hw_bench__DOT__dut__DOT__u_pse__DOT__unnamedblk1__DOT__base;
        SData/*15:0*/ tb_hw_bench__DOT__dut__DOT__u_pse__DOT__unnamedblk1__DOT__len;
        SData/*15:0*/ tb_hw_bench__DOT__dut__DOT__u_pse__DOT__unnamedblk1__DOT__w1;
        SData/*15:0*/ tb_hw_bench__DOT__dut__DOT__u_pse__DOT__unnamedblk1__DOT__w2;
        SData/*15:0*/ tb_hw_bench__DOT__dut__DOT__u_pse__DOT__unnamedblk1__DOT__idx1;
        SData/*15:0*/ tb_hw_bench__DOT__dut__DOT__u_pse__DOT__unnamedblk1__DOT__idx2;
        SData/*15:0*/ tb_hw_bench__DOT__dut__DOT__u_pse__DOT__unnamedblk1__DOT__repl_idx;
        SData/*15:0*/ tb_hw_bench__DOT__dut__DOT__u_pse__DOT__unnamedblk1__DOT__repl_head_idx;
        SData/*15:0*/ tb_hw_bench__DOT__dut__DOT__u_pse__DOT__unnamedblk1__DOT__old_head_idx;
        SData/*15:0*/ tb_hw_bench__DOT__dut__DOT__u_pse__DOT__unnamedblk1__DOT__cstart;
        SData/*15:0*/ tb_hw_bench__DOT__dut__DOT__u_pse__DOT__unnamedblk1__DOT__clen;
        SData/*15:0*/ __Vtrigprevexpr___TOP__tb_hw_bench__DOT__dut__DOT__trail_query_level__0;
        SData/*15:0*/ __Vtrigprevexpr___TOP__tb_hw_bench__DOT__dut__DOT__trail_query_level__1;
        IData/*31:0*/ tb_hw_bench__DOT__load_literal;
        IData/*31:0*/ tb_hw_bench__DOT__cycle_count;
        IData/*31:0*/ tb_hw_bench__DOT__decision_count;
        IData/*31:0*/ tb_hw_bench__DOT__conflict_count;
        IData/*31:0*/ tb_hw_bench__DOT__dut__DOT__resync_idx_q;
    };
    struct {
        IData/*31:0*/ tb_hw_bench__DOT__dut__DOT__resync_idx_d;
        IData/*31:0*/ tb_hw_bench__DOT__dut__DOT__last_decision_var_q;
        IData/*31:0*/ tb_hw_bench__DOT__dut__DOT__last_decision_var_d;
        IData/*31:0*/ tb_hw_bench__DOT__dut__DOT__trail_push_var;
        IData/*31:0*/ tb_hw_bench__DOT__dut__DOT__trail_backtrack_var;
        IData/*31:0*/ tb_hw_bench__DOT__dut__DOT__pse_propagated_var;
        IData/*31:0*/ tb_hw_bench__DOT__dut__DOT__pse_assign_broadcast_var;
        IData/*31:0*/ tb_hw_bench__DOT__dut__DOT__vde_decision_var;
        IData/*31:0*/ tb_hw_bench__DOT__dut__DOT__vde_assign_var;
        IData/*31:0*/ tb_hw_bench__DOT__dut__DOT__vde_max_var;
        IData/*31:0*/ tb_hw_bench__DOT__dut__DOT__vde_clear_var;
        IData/*31:0*/ tb_hw_bench__DOT__dut__DOT__decision_lit_q;
        IData/*31:0*/ tb_hw_bench__DOT__dut__DOT__decision_lit_d;
        IData/*31:0*/ tb_hw_bench__DOT__dut__DOT__unnamedblk5__DOT__prop_var;
        IData/*31:0*/ tb_hw_bench__DOT__dut__DOT__unnamedblk6__DOT__lit;
        IData/*31:0*/ tb_hw_bench__DOT__dut__DOT__unnamedblk6__DOT__var_idx;
        IData/*31:0*/ tb_hw_bench__DOT__dut__DOT__unnamedblk8__DOT__i;
        IData/*31:0*/ tb_hw_bench__DOT__dut__DOT__u_vde__DOT__best_act_q;
        IData/*31:0*/ tb_hw_bench__DOT__dut__DOT__u_vde__DOT__best_act_d;
        IData/*31:0*/ tb_hw_bench__DOT__dut__DOT__u_pse__DOT____Vlvbound_h65c98558__0;
        IData/*31:0*/ tb_hw_bench__DOT__dut__DOT__u_pse__DOT____Vlvbound_h5df078f0__0;
        IData/*31:0*/ tb_hw_bench__DOT__dut__DOT__u_pse__DOT__max_var_seen_q;
        IData/*31:0*/ tb_hw_bench__DOT__dut__DOT__u_pse__DOT__max_var_seen_d;
        IData/*31:0*/ tb_hw_bench__DOT__dut__DOT__u_pse__DOT__cur_prop_lit_q;
        IData/*31:0*/ tb_hw_bench__DOT__dut__DOT__u_pse__DOT__cur_prop_lit_d;
        IData/*31:0*/ tb_hw_bench__DOT__dut__DOT__u_pse__DOT__prop_push_val;
        IData/*31:0*/ tb_hw_bench__DOT__dut__DOT__u_pse__DOT__i;
        IData/*31:0*/ tb_hw_bench__DOT__dut__DOT__u_pse__DOT__unnamedblk1__DOT__v;
        IData/*31:0*/ tb_hw_bench__DOT__dut__DOT__u_pse__DOT__unnamedblk1__DOT__neg_lit;
        IData/*31:0*/ tb_hw_bench__DOT__dut__DOT__u_pse__DOT__unnamedblk1__DOT__lit1;
        IData/*31:0*/ tb_hw_bench__DOT__dut__DOT__u_pse__DOT__unnamedblk1__DOT__lit2;
        IData/*31:0*/ tb_hw_bench__DOT__dut__DOT__u_pse__DOT__unnamedblk1__DOT__lit_watch;
        IData/*31:0*/ tb_hw_bench__DOT__dut__DOT__u_pse__DOT__unnamedblk1__DOT__lit_other;
        IData/*31:0*/ tb_hw_bench__DOT__dut__DOT__u_pse__DOT__unnamedblk1__DOT__repl_lit;
        IData/*31:0*/ tb_hw_bench__DOT__dut__DOT__u_pse__DOT__unnamedblk1__DOT__l;
        IData/*31:0*/ tb_hw_bench__DOT__dut__DOT__u_pse__DOT__unnamedblk1__DOT__var_idx_b;
        IData/*31:0*/ tb_hw_bench__DOT__dut__DOT__u_pse__DOT__unnamedblk1__DOT__unnamedblk5__DOT__j;
        IData/*31:0*/ tb_hw_bench__DOT__dut__DOT__u_pse__DOT__unnamedblk7__DOT__var_idx;
        IData/*31:0*/ tb_hw_bench__DOT__dut__DOT__u_cae__DOT__uip_lit;
        IData/*31:0*/ tb_hw_bench__DOT__dut__DOT__u_cae__DOT__vidx;
        IData/*31:0*/ __Vfunc_tb_hw_bench__DOT__dut__DOT__u_pse__DOT__lit_truth__1__lit;
        IData/*31:0*/ __Vfunc_tb_hw_bench__DOT__dut__DOT__u_pse__DOT__lit_truth__1__v;
        IData/*31:0*/ __Vfunc_tb_hw_bench__DOT__dut__DOT__u_pse__DOT__lit_truth__2__lit;
        IData/*31:0*/ __Vfunc_tb_hw_bench__DOT__dut__DOT__u_pse__DOT__lit_truth__2__v;
        IData/*31:0*/ __Vfunc_tb_hw_bench__DOT__dut__DOT__u_cae__DOT__abs_lit__3__Vfuncout;
        IData/*31:0*/ __Vfunc_tb_hw_bench__DOT__dut__DOT__u_cae__DOT__abs_lit__3__lit;
        IData/*31:0*/ __Vfunc_tb_hw_bench__DOT__dut__DOT__u_cae__DOT__abs_lit__4__Vfuncout;
        IData/*31:0*/ __Vfunc_tb_hw_bench__DOT__dut__DOT__u_cae__DOT__abs_lit__4__lit;
        IData/*31:0*/ __Vtrigprevexpr___TOP__tb_hw_bench__DOT__dut__DOT__pse_assign_broadcast_var__0;
        IData/*31:0*/ __Vtrigprevexpr___TOP__tb_hw_bench__DOT__dut__DOT__pse_assign_broadcast_var__1;
        IData/*31:0*/ __VactIterCount;
        VlUnpacked<IData/*31:0*/, 8> tb_hw_bench__DOT__dut__DOT__pse_conflict_clause;
        VlUnpacked<IData/*31:0*/, 8> tb_hw_bench__DOT__dut__DOT__conflict_clause_q;
        VlUnpacked<IData/*31:0*/, 8> tb_hw_bench__DOT__dut__DOT__conflict_clause_d;
        VlUnpacked<CData/*7:0*/, 8> tb_hw_bench__DOT__dut__DOT__conflict_levels_q;
        VlUnpacked<CData/*7:0*/, 8> tb_hw_bench__DOT__dut__DOT__conflict_levels_d;
        VlUnpacked<IData/*31:0*/, 8> tb_hw_bench__DOT__dut__DOT__cae_learned_lits;
        VlUnpacked<IData/*31:0*/, 8> tb_hw_bench__DOT__dut__DOT__vde_bump_vars;
        VlUnpacked<IData/*31:0*/, 64> tb_hw_bench__DOT__dut__DOT__u_vde__DOT__activity;
        VlUnpacked<CData/*0:0*/, 64> tb_hw_bench__DOT__dut__DOT__u_vde__DOT__assigned;
        VlUnpacked<CData/*0:0*/, 64> tb_hw_bench__DOT__dut__DOT__u_vde__DOT__phase_hint;
        VlUnpacked<QData/*49:0*/, 64> tb_hw_bench__DOT__dut__DOT__u_trail__DOT__trail;
        VlUnpacked<SData/*15:0*/, 64> tb_hw_bench__DOT__dut__DOT__u_trail__DOT__var_to_level;
        VlUnpacked<SData/*15:0*/, 64> tb_hw_bench__DOT__dut__DOT__u_trail__DOT__var_to_level_d;
    };
    struct {
        VlUnpacked<CData/*1:0*/, 64> tb_hw_bench__DOT__dut__DOT__u_pse__DOT__assign_state;
        VlUnpacked<SData/*15:0*/, 192> tb_hw_bench__DOT__dut__DOT__u_pse__DOT__clause_len;
        VlUnpacked<SData/*15:0*/, 192> tb_hw_bench__DOT__dut__DOT__u_pse__DOT__clause_start;
        VlUnpacked<IData/*31:0*/, 516> tb_hw_bench__DOT__dut__DOT__u_pse__DOT__lit_mem;
        VlUnpacked<SData/*15:0*/, 192> tb_hw_bench__DOT__dut__DOT__u_pse__DOT__watched_lit1;
        VlUnpacked<SData/*15:0*/, 192> tb_hw_bench__DOT__dut__DOT__u_pse__DOT__watched_lit2;
        VlUnpacked<SData/*15:0*/, 192> tb_hw_bench__DOT__dut__DOT__u_pse__DOT__watched_lit1_d;
        VlUnpacked<SData/*15:0*/, 192> tb_hw_bench__DOT__dut__DOT__u_pse__DOT__watched_lit2_d;
        VlUnpacked<SData/*15:0*/, 128> tb_hw_bench__DOT__dut__DOT__u_pse__DOT__watch_head1;
        VlUnpacked<SData/*15:0*/, 128> tb_hw_bench__DOT__dut__DOT__u_pse__DOT__watch_head2;
        VlUnpacked<SData/*15:0*/, 128> tb_hw_bench__DOT__dut__DOT__u_pse__DOT__watch_head1_d;
        VlUnpacked<SData/*15:0*/, 128> tb_hw_bench__DOT__dut__DOT__u_pse__DOT__watch_head2_d;
        VlUnpacked<SData/*15:0*/, 192> tb_hw_bench__DOT__dut__DOT__u_pse__DOT__watch_next1;
        VlUnpacked<SData/*15:0*/, 192> tb_hw_bench__DOT__dut__DOT__u_pse__DOT__watch_next2;
        VlUnpacked<SData/*15:0*/, 192> tb_hw_bench__DOT__dut__DOT__u_pse__DOT__watch_next1_d;
        VlUnpacked<SData/*15:0*/, 192> tb_hw_bench__DOT__dut__DOT__u_pse__DOT__watch_next2_d;
        VlUnpacked<IData/*31:0*/, 516> tb_hw_bench__DOT__dut__DOT__u_pse__DOT__prop_q;
        VlUnpacked<IData/*31:0*/, 8> tb_hw_bench__DOT__dut__DOT__u_cae__DOT__learned_tmp;
        VlUnpacked<QData/*63:0*/, 2> __VstlTriggered;
        VlUnpacked<QData/*63:0*/, 1> __VactTriggered;
        VlUnpacked<QData/*63:0*/, 1> __VnbaTriggered;
    };
    VlNBACommitQueue<VlUnpacked<SData/*15:0*/, 192>, false, SData/*15:0*/, 1> __VdlyCommitQueuetb_hw_bench__DOT__dut__DOT__u_pse__DOT__watched_lit1;
    VlNBACommitQueue<VlUnpacked<SData/*15:0*/, 192>, false, SData/*15:0*/, 1> __VdlyCommitQueuetb_hw_bench__DOT__dut__DOT__u_pse__DOT__watched_lit2;
    VlNBACommitQueue<VlUnpacked<SData/*15:0*/, 192>, false, SData/*15:0*/, 1> __VdlyCommitQueuetb_hw_bench__DOT__dut__DOT__u_pse__DOT__watch_next1;
    VlNBACommitQueue<VlUnpacked<SData/*15:0*/, 192>, false, SData/*15:0*/, 1> __VdlyCommitQueuetb_hw_bench__DOT__dut__DOT__u_pse__DOT__watch_next2;
    VlNBACommitQueue<VlUnpacked<SData/*15:0*/, 128>, false, SData/*15:0*/, 1> __VdlyCommitQueuetb_hw_bench__DOT__dut__DOT__u_pse__DOT__watch_head1;
    VlNBACommitQueue<VlUnpacked<SData/*15:0*/, 128>, false, SData/*15:0*/, 1> __VdlyCommitQueuetb_hw_bench__DOT__dut__DOT__u_pse__DOT__watch_head2;
    VlDelayScheduler __VdlySched;
    VlTriggerScheduler __VtrigSched_h09a47e26__0;

    // INTERNAL VARIABLES
    Vtb_hw_bench__Syms* vlSymsp;
    const char* vlNamep;

    // CONSTRUCTORS
    Vtb_hw_bench___024root(Vtb_hw_bench__Syms* symsp, const char* namep);
    ~Vtb_hw_bench___024root();
    VL_UNCOPYABLE(Vtb_hw_bench___024root);

    // INTERNAL METHODS
    void __Vconfigure(bool first);
};


#endif  // guard
